(() => {
  const TRIALS=100;
  function freshParty(){if(typeof window.makeParty==='function')return window.makeParty();const factory=new CharacterFactory();return (window.DUMMY_PARTY||[]).map(x=>factory.create({...x,team:'player'}));}
  function monstersFor(dungeon,area,rng){const p=dungeon?.areas?.find(x=>x.area===area);const e=p?.encounters?.length?p.encounters[rng.int(0,p.encounters.length-1)]:null;if(e?.enemies?.length)return e.enemies.map(m=>window.MonsterXmlLoader?.state?.items?.find(x=>x.dungeonName===dungeon.monsterDungeonName&&x.name===m.name)).filter(Boolean);return[];}
  function runOne(dungeon,area,seed){const rng=new SeededRandom(seed),party=freshParty(),ms=monstersFor(dungeon,area,rng);if(!ms.length)return null;const enemies=ms.map((m,i)=>new Character({id:`balance-${m.id}-${seed}-${i}`,name:m.name,hp:m.maxHp,maxHp:m.maxHp,attack:m.attack,defense:m.defense,speed:10,team:'enemy',exp:m.exp,level:m.level,monsterId:m.id,monsterGrade:m.grade,monsterForm:m.form}));const result=new BattleEngine({rng,damageCalculator:new DamageCalculator(rng)}).run(party,enemies);return{win:result.result==='WIN',dead:!party.some(c=>c.alive),rounds:result.round,enemies};}
  function render(dungeon){const modal=document.getElementById('logDetail');if(!modal||!dungeon)return;const rows=[];for(let area=1;area<=(dungeon.floors||dungeon.areas?.length||0);area++){const rs=[];for(let i=0;i<TRIALS;i++){const r=runOne(dungeon,area,Number(window.state?.seed||12345)+area*1000+i);if(r)rs.push(r);}if(!rs.length)continue;const wins=rs.filter(x=>x.win).length,avg=Math.round(rs.reduce((n,x)=>n+x.rounds,0)/rs.length*10)/10,deaths=rs.filter(x=>x.dead).length,m=rs[0].enemies;rows.push(`<div class="detail-line"><b>${area}구역 · ${m.map(x=>x.name).join(', ')}</b><br>승률 ${wins}% · 평균 ${avg}R · 파티 전멸 ${deaths}%<br>레벨 ${m.map(x=>x.level).join('/')} · HP ${m.map(x=>Math.round(x.hp)).join('/')} · ATK ${m.map(x=>Math.round(x.attack)).join('/')} · DEF ${m.map(x=>Math.round(x.defense)).join('/')} · EXP ${m.map(x=>Math.round(x.exp)).join('/')}</div>`);}modal.innerHTML=`<div class="modal-card"><button type="button" class="close" aria-label="닫기">×</button><h2>${dungeon.name} · 밸런스 테스트</h2><p>구역별 ${TRIALS}회 실전 전투 시뮬레이션</p><div class="detail-body">${rows.join('')||'<p>몬스터 배치 데이터를 불러오지 못했습니다.</p>'}</div></div>`;modal.hidden=false;modal.querySelector('.close').addEventListener('click',()=>modal.hidden=true);modal.addEventListener('click',ev=>{if(ev.target===modal)modal.hidden=true},{once:true});}
  window.DungeonBalancePanel={render};
})();

(() => {
  const registry=window.SKILL_REGISTRY||{};registry['party-heal']={id:'party-heal',name:'HEAL',classId:'mage',cooldown:3,healPercent:0.15,target:'party',description:'전투 중 아군 전체의 최대 HP 15%를 회복합니다.'};window.SKILL_REGISTRY=registry;if(window.CHARACTER_CLASSES?.mage)window.CHARACTER_CLASSES.mage.skills=Array.from(new Set([...(window.CHARACTER_CLASSES.mage.skills||[]),'party-heal']));if(!window.BattleEngine)return;const originalChooseSkill=BattleEngine.prototype.chooseSkill,originalResolveAttack=BattleEngine.prototype.resolveAttack;BattleEngine.prototype.chooseSkill=function(actor,state){if((state.cooldowns[actor.id]||0)>0)return null;const ids=Array.isArray(actor.skills)?actor.skills:[],available=ids.map(id=>registry[id]).filter(Boolean);if(!available.length)return originalChooseSkill.call(this,actor,state);const heal=available.find(skill=>skill.target==='party'&&Number(skill.healPercent)>0);if(heal&&actor.team==='player'&&state.players.filter(c=>c.alive).some(c=>Number(c.hp)<Number(c.maxHp)*0.85))return heal;return available.find(skill=>skill.target!=='party')||originalChooseSkill.call(this,actor,state);};BattleEngine.prototype.resolveAttack=function(attacker,defender,state,skill=null){if(skill?.target==='party'&&Number(skill.healPercent)>0&&attacker.team==='player'){const healed=state.players.filter(c=>c.alive).map(c=>{const beforeHp=Number(c.hp)||0,amount=Math.max(0,Math.ceil(Number(c.maxHp||0)*Number(skill.healPercent)));c.hp=Math.min(c.maxHp,beforeHp+amount);return{id:c.id,name:c.name,beforeHp,afterHp:c.hp,amount:c.hp-beforeHp,maxHp:c.maxHp};});this.emit(state,'HEAL',{actorId:attacker.id,actor:attacker.name,skillId:skill.id,skill:skill.name,percent:Number(skill.healPercent)*100,targets:healed});return;}return originalResolveAttack.call(this,attacker,defender,state,skill);};
})();
