class PartyPanel {
  constructor({container,party,run}){this.container=container;this.party=party;this.run=run;window.activePartyPanel=this;}
  getInventory(){return typeof window.shopInventory==='function' ? window.shopInventory() : Object.values(window.EQUIPMENT||{});}
  getClassName(c){return ({warrior:'전사',mage:'마법사',rogue:'도적'})[c.classId]||c.classId||'모험가';}
  expInfo(c){const need=typeof c.expToNextLevel==='function'?c.expToNextLevel():Math.max(100,(c.level||1)*100);const exp=Math.max(0,Number(c.exp)||0);return {exp,need,percent:Math.min(100,exp/need*100)};}
  isInstanceEquipped(instanceId,exceptCharacterId=null){return !!this.party?.some(c=>c.id!==exceptCharacterId&&Object.values(c.equipment||{}).some(item=>item?.instanceId===instanceId));}
  render(){
    if(!this.container)return;
    const rows=this.party.map(c=>{const s=this.run?.stats?.[c.id]||c.stats||{},dps=this.run?.getDps?.(c.id)||0,hp=Math.max(0,c.hp),max=Math.max(1,c.maxHp),eq=c.equipment||{},xp=this.expInfo(c);const equipButton=(slot,label)=>{const item=eq[slot];return `<button type="button" class="inn-equip-btn" data-detail="${c.id}"><span class="inn-equip-icon">${slot==='weapon'?'⚔':slot==='armor'?'🛡':'💍'}</span><span>${item?.name||label}</span></button>`;};return `<article class="inn-party-card ${c.alive?'':'down'}"><button type="button" class="inn-character-main" data-id="${c.id}"><span class="inn-portrait">${c.appearance?.portrait||'?'}</span><span class="inn-character-info"><b>${c.name}</b><small>${this.getClassName(c)} · Lv.${c.level||1} · Exp ${xp.exp.toLocaleString()}/${xp.need.toLocaleString()}</small><span class="inn-hp"><i style="width:${Math.min(100,hp/max*100)}%"></i></span><small>HP ${hp}/${max} · DPS ${dps} · DMG ${s.damage||s.damageDealt||0}</small><span class="inn-xp"><i style="width:${xp.percent}%"></i></span></span></button><div class="inn-equipment">${equipButton('weapon','무기 미장착')}${equipButton('armor','방어구 미장착')}${equipButton('accessory','장신구 미장착')}</div></article>`;}).join('');
    const inventory=this.getInventory();const invHtml=inventory.length?inventory.map(item=>`<div class="inn-inventory-item"><span>${item.slot==='weapon'?'⚔':item.slot==='armor'?'🛡':'💍'}</span><span><b>${item.name}</b><small>#${item.instanceId||item.id} · 공 ${item.attack||0} · 방 ${item.defense||0} · 속 ${item.speed||0}${item.instanceId&&this.isInstanceEquipped(item.instanceId)?' · 장착 중':''}</small></span></div>`).join(''):'<p class="muted">보유 장비가 없습니다.</p>';
    this.container.innerHTML=`<div class="inn-party-list">${rows}</div><section class="inn-inventory"><div class="inn-section-title">보유 장비 <small>${inventory.length}개</small></div>${invHtml}</section>`;
    this.container.querySelectorAll('[data-id]').forEach(el=>el.onclick=()=>this.showDetail(el.dataset.id));this.container.querySelectorAll('[data-detail]').forEach(el=>el.onclick=()=>this.showDetail(el.dataset.detail));
  }
  showDetail(id){
    const c=this.party.find(x=>x.id===id);if(!c)return;const s=this.run?.stats?.[id]||c.stats||{},dps=this.run?.getDps?.(id)||0,detail=document.getElementById('characterDetail');if(!detail)return;const slots=window.EQUIPMENT_SLOTS||{},items=this.getInventory(),xp=this.expInfo(c);
    const equipHtml=Object.entries(slots).map(([slot,label])=>{const current=c.equipment?.[slot];const opts=items.filter(x=>x.slot===slot && (x.instanceId===current?.instanceId || !this.isInstanceEquipped(x.instanceId,c.id))).map(x=>`<option value="${x.instanceId}" ${current?.instanceId===x.instanceId?'selected':''}>${x.name} [#${x.instanceId}] (+공${x.attack||0} / +방${x.defense||0} / 속${x.speed||0})</option>`).join('');return `<label class="equip-row"><span>${label}</span><select onchange="window.equipCharacterItem('${c.id}','${slot}',this.value)"><option value="">없음</option>${opts}</select></label>`}).join('');
    const combatHtml=`<section class="character-combat"><b>전투 기록</b><dl><dt>현재 DPS</dt><dd>${dps}</dd><dt>누적 Damage</dt><dd>${s.damage||s.damageDealt||0}</dd><dt>공격 / 명중 / 치명타</dt><dd>${s.attacks||0} / ${s.hits||0} / ${s.criticals||0}</dd><dt>피격 Damage</dt><dd>${s.damageTaken||0}</dd><dt>처치</dt><dd>${s.kills||0}</dd></dl></section>`;
    detail.innerHTML=`<div class="modal-card character-modal-card"><button class="close" type="button" aria-label="닫기">×</button><div class="character-modal-head"><span class="inn-portrait">${c.appearance?.portrait||'?'}</span><div><h3>${c.name}</h3><p>${this.getClassName(c)} · Lv.${c.level||1} · Exp ${xp.exp}/${xp.need}</p></div></div><div class="character-overview"><section class="character-stats"><b>현재 상태</b><dl><dt>HP</dt><dd>${c.hp}/${c.maxHp}</dd><dt>공격</dt><dd>${c.attack} <small>(기본 ${c.baseStats?.attack??c.attack})</small></dd><dt>방어</dt><dd>${c.defense} <small>(기본 ${c.baseStats?.defense??c.defense})</small></dd><dt>속도</dt><dd>${c.speed}</dd></dl></section>${combatHtml}</div><section class="character-equipment"><b>장비 장착</b>${equipHtml}</section></div>`;
    const close=()=>{detail.hidden=true;detail.innerHTML='';};detail.querySelector('.close').onclick=close;detail.onclick=e=>{if(e.target===detail)close();};detail.hidden=false;
  }
}
window.equipCharacterItem=function(characterId,slot,itemInstanceId){const p=window.activePartyPanel,c=p?.party?.find(x=>x.id===characterId);if(!c)return;if(!itemInstanceId){c.unequip(slot);p.render();p.showDetail(characterId);window.shopRender?.();return;}const item=window.getEquipmentInstance?.(itemInstanceId)||null;if(!item||!item.instanceId||!window.isEquipmentOwned?.(item.instanceId))return;if(p.isInstanceEquipped(item.instanceId,characterId)){const s=document.getElementById('status');if(s)s.textContent='이 장비는 다른 캐릭터가 장착 중입니다.';p.showDetail(characterId);return;}c.unequip(slot);c.equip(item);p.render();p.showDetail(characterId);window.shopRender?.();};
window.PartyPanel=PartyPanel;
window.addEventListener('DOMContentLoaded',()=>{const buttons=[...document.querySelectorAll('.tabs button[data-tab]')];const activate=id=>{buttons.forEach(b=>{const active=b.dataset.tab===id;b.classList.toggle('active',active);b.setAttribute('aria-selected',active?'true':'false');const panel=document.getElementById(b.dataset.tab);if(panel)panel.classList.toggle('active',active);});if(id==='innTab'){window.activePartyPanel?.render?.();window.renderQuests?.();}if(id==='shopTab')window.shopRender?.();};buttons.forEach(b=>b.addEventListener('click',e=>{e.preventDefault();activate(b.dataset.tab);}));const main=document.getElementById('mainQuestTab'),repeat=document.getElementById('repeatQuestTab');if(main)main.addEventListener('click',()=>{window.questUISetMode?.('main');window.renderQuests?.();});if(repeat)repeat.addEventListener('click',()=>{window.questUISetMode?.('repeat');window.renderQuests?.();});activate('dungeonTab');});
