(() => {
  const SHOP_PRICES={iron_sword:60,oak_staff:70,hunter_dagger:65,leather_armor:80,adventurer_ring:120,iron_armor:180}; const SELL_RATE=0.5; const starter=new Set(window.STARTER_EQUIPMENT||[]); const owned=new Map(); let nextInstanceNo=1;
  const makeInstanceId=baseId=>`itm_${baseId}_${Date.now().toString(36)}_${nextInstanceNo++}`; const createInstance=(base,instanceId,extra={})=>({...base,instanceId:instanceId||makeInstanceId(base.id),baseId:base.id,enhancement:0,options:[],...extra});
  for(const id of starter)if(window.EQUIPMENT?.[id]){const item=createInstance(window.EQUIPMENT[id],`starter_${id}`);owned.set(item.instanceId,item);}
  function getItems(){return Object.values(window.EQUIPMENT||{}).filter(x=>SHOP_PRICES[x.id]!=null);} function getInventory(){return [...owned.values()];}
  function currentRun(){const r=window.run||window.activePartyPanel?.run||null;if(r&&!r.__shopGoldInitialized){if(Number(r.gold)===0)r.gold=100;r.__shopGoldInitialized=true;}return r;} function getGold(){return Number(currentRun()?.gold??0);} function syncInventory(){window.playerInventory=getInventory();}
  function findEquipped(instanceId){const run=currentRun(); if(!run?.party)return null; for(const c of run.party){for(const [slot,item] of Object.entries(c.equipment||{})){if(item?.instanceId===instanceId)return {character:c,slot};}} return null;}
  function isEquipped(instanceId){return !!findEquipped(instanceId);} function formatItem(item){const opts=(item.options||[]).map(o=>`${o.name} +${o.value}`).join(', ');return `${item.name}${item.enhancement?` +${item.enhancement}`:''}${item.rarityName?` · ${item.rarityName}`:''}${opts?` · ${opts}`:''}`;}
  function renderShop(){const root=document.getElementById('shop');if(!root)return;syncInventory();const gold=getGold();const shopHtml=getItems().map(item=>{const qty=getInventory().filter(x=>x.baseId===item.id).length,price=SHOP_PRICES[item.id],stats=[`공 ${item.attack||0}`,`방 ${item.defense||0}`,`속 ${item.speed||0}`].join(' · ');return `<div class="shop-item"><div class="shop-item-main"><b>${item.name}${qty?` ×${qty}`:''}</b><small>${stats} · ${item.rarity||'common'} · ${price}G</small></div><button type="button" data-buy-item="${item.id}" ${gold<price?'disabled':''}>구매</button></div>`;}).join('');const invHtml=getInventory().map(item=>{const price=Math.floor((SHOP_PRICES[item.baseId]||SHOP_PRICES[item.id]||0)*SELL_RATE),equipped=isEquipped(item.instanceId),sellable=price>0;return `<div class="shop-item"><div class="shop-item-main"><b>${formatItem(item)}</b><small>#${item.instanceId} · 공 ${item.attack||0} · 방 ${item.defense||0} · 속 ${item.speed||0}${equipped?' · 장착 중':' '}</small></div><button type="button" data-sell-instance="${item.instanceId}" ${!sellable?'disabled':''}>${equipped?'장착 해제 후 매각':'매각'}</button></div>`;}).join('')||'<p class="muted">보유 장비가 없습니다.</p>';root.innerHTML=`<div class="currency-line">보유 골드 <b>${gold.toLocaleString()} G</b></div><h3>장비 구매</h3>${shopHtml||'<p>판매할 장비가 없습니다.</p>'}<h3>보유 장비 · 매각</h3>${invHtml}`;root.querySelectorAll('[data-buy-item]').forEach(btn=>btn.addEventListener('click',()=>buyItem(btn.dataset.buyItem)));root.querySelectorAll('[data-sell-instance]').forEach(btn=>btn.addEventListener('click',()=>sellInstance(btn.dataset.sellInstance)));}
  function buyItem(id){const item=window.EQUIPMENT?.[id],price=SHOP_PRICES[id],run=currentRun(),gold=getGold();if(!item||price==null||!run||gold<price)return;run.gold=gold-price;const instance=createInstance(item);owned.set(instance.instanceId,instance);syncInventory();renderShop();window.activePartyPanel?.render?.();const s=document.getElementById('status');if(s)s.textContent=`${item.name} 구매 완료 · ${price}G · #${instance.instanceId}`;}
  function addLootInstance(item){if(!item?.instanceId)return false;owned.set(item.instanceId,item);syncInventory();renderShop();window.activePartyPanel?.render?.();return true;}
  function sellInstance(instanceId){const item=owned.get(instanceId),price=Math.floor((SHOP_PRICES[item?.baseId||item?.id]||0)*SELL_RATE),run=currentRun();if(!item||price<=0||!run)return;const equipped=findEquipped(instanceId);if(equipped){equipped.character.unequip?.(equipped.slot);if(equipped.character.equipment?.[equipped.slot])equipped.character.equipment[equipped.slot]=null;equipped.character.recalculateStats?.();}owned.delete(instanceId);run.gold=getGold()+price;syncInventory();renderShop();window.activePartyPanel?.render?.();const s=document.getElementById('status');if(s)s.textContent=`${item.name}${equipped?' · 장착 해제':' '} 매각 완료 · +${price}G`;}
  function openLootTest(){let modal=document.getElementById('lootTestModal');if(!modal){modal=document.createElement('div');modal.id='lootTestModal';modal.className='modal';modal.hidden=true;modal.innerHTML=`<div class="modal-card" style="max-width:430px"><button class="close" type="button" data-close-loot>×</button><h2>Loot 테스트</h2><div style="font-size:11px;line-height:1.5">등급 언커먼 60% · 커먼 25% · 레어 10% · 유니크 4% · 전설 1%<br>강화 +0 80% · +1 15% · +2 5%</div><label style="display:block;margin:8px 0">장비 레벨 <input id="lootTestLevel" type="number" min="1" value="50" style="width:100%;min-height:36px"></label><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:4px"><button type="button" data-loot-count="1">1회</button><button type="button" data-loot-count="100">100회</button><button type="button" data-loot-count="1000">1,000회</button></div><pre id="lootTestResult" style="white-space:pre-wrap;overflow:auto;max-height:55vh;font-size:11px;line-height:1.4"></pre></div>`;document.body.appendChild(modal);modal.addEventListener('click',e=>{if(e.target===modal||e.target.closest('[data-close-loot]'))modal.hidden=true;if(e.target.matches('[data-loot-count]'))runLootTest(Number(e.target.dataset.lootCount));});}modal.hidden=false;}
  function runLootTest(count){const out=document.getElementById('lootTestResult');if(!window.LootSystem||!window.SeededRandom){out.textContent='LootSystem 또는 SeededRandom을 불러오지 못했습니다.';return}const level=Math.max(1,Number(document.getElementById('lootTestLevel')?.value)||1),rng=new SeededRandom(Number(document.getElementById('seed')?.value)||12345),rarity={common:0,uncommon:0,rare:0,unique:0,legendary:0},enh={0:0,1:0,2:0};let last=null;for(let i=0;i<count;i++){last=LootSystem.generate({rng,force:true});if(last){rarity[last.rarity]=(rarity[last.rarity]||0)+1;enh[last.enhancement]=(enh[last.enhancement]||0)+1;}}const pct=o=>Object.fromEntries(Object.entries(o).map(([k,v])=>[k,(v/count*100).toFixed(2)+'%']));out.textContent=JSON.stringify({level,samples:count,rarity,rarityPercent:pct(rarity),enhancement:enh,enhancementPercent:pct(enh),lastDrop:last},null,2);}
  window.shopRender=renderShop;window.shopInventory=()=>getInventory();window.shopBuy=buyItem;window.shopSell=sellInstance;window.addLootInstance=addLootInstance;window.isEquipmentOwned=id=>getInventory().some(x=>x.instanceId===id||x.baseId===id);window.getEquipmentQuantity=id=>getInventory().filter(x=>x.baseId===id||x.id===id).length;window.getEquipmentInstance=id=>owned.get(id)||null;
  window.addEventListener('DOMContentLoaded',()=>{syncInventory();renderShop();const toolbar=document.querySelector('.toolbar');if(toolbar&&!document.getElementById('lootTestLauncher')){const b=document.createElement('button');b.id='lootTestLauncher';b.type='button';b.textContent='Loot 테스트';b.style.cssText='grid-column:1 / -1;min-height:38px;font-size:12px';b.addEventListener('click',openLootTest);toolbar.appendChild(b);}});
})();
