package com.shirobakama.autorpg2.repo;

import android.content.Context;
import com.shirobakama.autorpg2.entity.GameChar;
import com.shirobakama.autorpg2.entity.Item;
import com.shirobakama.autorpg2.entity.Monster;
import com.shirobakama.logquest2.C0380R;

/* loaded from: D:\Android_hobby\작업중\com.shirobakama.logquest2-1.3.13\classes.dex */
public final class ItemDb {
    public static final int ITEM_AIGIS = 3050;
    public static final int ITEM_AMANOMURAKUMO = 1290;
    public static final int ITEM_ANDURIL = 1380;
    public static final int ITEM_ASTRO_BOOK = 5100;
    public static final int ITEM_BATTLE_AXE = 1170;
    public static final int ITEM_BATTLE_DRESS = 2100;
    public static final int ITEM_BEAR_HAND = 1010;
    public static final int ITEM_BOW_OF_SHEKINAH = 1510;
    public static final int ITEM_BREAST_PLATE = 2050;
    public static final int ITEM_BUCKLER = 3010;
    public static final int ITEM_CHAIN_MAIL = 2040;
    public static final int ITEM_CLAYMORE = 1260;
    public static final int ITEM_CLUB = 1020;
    public static final int ITEM_COMPOSITE_BOW = 1220;
    public static final int ITEM_DAGGER = 1060;
    public static final int ITEM_DAGGER_OF_THIEVES = 1540;
    public static final int ITEM_DEMON_AMULET = 5060;
    public static final int ITEM_DRAGON_SCALE = 2090;
    public static final int ITEM_DRAGON_SLAYER = 1350;
    public static final int ITEM_DURANDAL = 1430;
    public static final int ITEM_DWARVEN_ANVIL = 5150;
    public static final int ITEM_ELVEN_BOW = 1530;
    public static final int ITEM_ERIRIL = 1570;
    public static final int ITEM_EXCALIBUR = 1280;
    public static final int ITEM_FALCHION = 1160;
    public static final int ITEM_FIGHTER_SYMBOL = 5110;
    public static final int ITEM_GAEBOLG = 1500;
    public static final int ITEM_GARB_OF_LORDS = 2110;
    public static final int ITEM_GIANT_CLUB = 1100;
    public static final int ITEM_GLADIUS = 1080;
    public static final int ITEM_GLAMDRING = 1390;
    public static final int ITEM_GRAM = 1460;
    public static final int ITEM_GRAYSWANDIR = 1400;
    public static final int ITEM_GRAYWAND = 1330;
    public static final int ITEM_GREAT_SWORD = 1190;
    public static final int ITEM_GUNGNIR = 1490;
    public static final int ITEM_HALBARD = 1230;
    public static final int ITEM_HAND_AXE = 1130;
    public static final int ITEM_HIGHEST_MAGIC_POTION = 60;
    public static final int ITEM_HIGHEST_POTION = 50;
    public static final int ITEM_HIGH_MAGIC_POTION = 40;
    public static final int ITEM_HIGH_POTION = 30;
    public static final int ITEM_HOLY_SYMBOL = 5130;
    public static final int ITEM_KINGDOM_ORDER = 5070;
    public static final int ITEM_LAEVATEINN = 1470;
    public static final int ITEM_LAMELLAR = 2070;
    public static final int ITEM_LARGE_SHIELD = 3030;
    public static final int ITEM_LEATHER_ARMOR = 2020;
    public static final int ITEM_LINK_SHIELD = 3070;
    public static final int ITEM_LONG_BOW = 1210;
    public static final int ITEM_LONG_SWORD = 1090;
    public static final int ITEM_MACE = 1120;
    public static final int ITEM_MAGIC_BOOK = 5140;
    public static final int ITEM_MAGIC_POTION = 20;
    public static final int ITEM_MAGIC_STAFF = 1550;
    public static final int ITEM_MEDAL_OF_LORDS = 5080;
    public static final int ITEM_MITHRIL_CHAIN = 2080;
    public static final int ITEM_MJOLNIR = 1410;
    public static final int ITEM_MONSTERS_JEWEL = 5170;
    public static final int ITEM_MOURNBLADE = 1420;
    public static final int ITEM_MURAMASA_BLADE = 1480;
    public static final int ITEM_NAGINATA = 1270;
    public static final int ITEM_NINJA_KATANA = 1240;
    public static final int ITEM_OGRE_KILLER = 1370;
    public static final int ITEM_ORC_SLAYER = 1300;
    public static final int ITEM_PAPER_FOLDER = 5040;
    public static final int ITEM_PLATE_ARMOR = 2060;
    public static final int ITEM_POTION = 10;
    public static final int ITEM_PRYTWEN = 3060;
    public static final int ITEM_PURPLE_FLOWER = 5020;
    public static final int ITEM_RAIJODO = 1520;
    public static final int ITEM_RAPIER = 1180;
    public static final int ITEM_RHONGOMIANT = 1440;
    public static final int ITEM_RING_MAIL = 2030;
    public static final int ITEM_RING_OF_AGI = 4040;
    public static final int ITEM_RING_OF_AGI2 = 4080;
    public static final int ITEM_RING_OF_CRITICAL = 4120;
    public static final int ITEM_RING_OF_DEFENSE = 4090;
    public static final int ITEM_RING_OF_DODGE = 4110;
    public static final int ITEM_RING_OF_HITTING = 4100;
    public static final int ITEM_RING_OF_INT = 4030;
    public static final int ITEM_RING_OF_INT2 = 4070;
    public static final int ITEM_RING_OF_STR = 4010;
    public static final int ITEM_RING_OF_STR2 = 4050;
    public static final int ITEM_RING_OF_VIT = 4020;
    public static final int ITEM_RING_OF_VIT2 = 4060;
    public static final int ITEM_ROBE = 2010;
    public static final int ITEM_RUSTED_KEY = 5010;
    public static final int ITEM_SAMURAI_BLADE = 1250;
    public static final int ITEM_SCALPEL = 1340;
    public static final int ITEM_SECRET_SCROLL = 5090;
    public static final int ITEM_SHORT_BOW = 1200;
    public static final int ITEM_SHORT_SWORD = 1070;
    public static final int ITEM_SILVER_HANDLE = 5030;
    public static final int ITEM_SLING = 1030;
    public static final int ITEM_SLING_STAFF = 1040;
    public static final int ITEM_SMALL_SHIELD = 3020;
    public static final int ITEM_SORCERERS_STAFF = 1560;
    public static final int ITEM_SOUL_AMULET = 5050;
    public static final int ITEM_SPEAR = 1140;
    public static final int ITEM_STAFF = 1050;
    public static final int ITEM_SYNTHETIC_CATALYST = 5160;
    public static final int ITEM_TERMINUS_EST = 1320;
    public static final int ITEM_THIEVES_GUILD = 5120;
    public static final int ITEM_TOWER_SHIELD = 3040;
    public static final int ITEM_TRAITOR = 1450;
    public static final int ITEM_TRIDENT = 1150;
    public static final int ITEM_UNDEAD_SLAYER = 1310;
    public static final int ITEM_WAR_HAMMER = 1110;
    public static final int ITEM_WERE_SLAYER = 1360;

    static void initialize(Context context) {
        ItemRepository.addItem(ItemRepository.create(Item.Type.CONSUMABLE, 10, "potion", C0380R.string.res_item_potion, C0380R.drawable.item_potion, C0380R.string.res_item_potion_desc, 80, 4, 3, 1, false));
        ItemRepository.addItem(ItemRepository.create(Item.Type.CONSUMABLE, 20, "magic_potion", C0380R.string.res_item_magic_potion, C0380R.drawable.item_magic_potion, C0380R.string.res_item_magic_potion_desc, MonsterDb.MONSTER_STIRGE, 6, 3, 2, false));
        ItemRepository.addItem(ItemRepository.create(Item.Type.CONSUMABLE, 30, "high_potion", C0380R.string.res_item_high_potion, C0380R.drawable.item_high_potion, C0380R.string.res_item_high_potion_desc, 400, 6, 4, 3, false));
        ItemRepository.addItem(ItemRepository.create(Item.Type.CONSUMABLE, 40, "high_magic_potion", C0380R.string.res_item_high_magic_potion, C0380R.drawable.item_high_magic_potion, C0380R.string.res_item_high_magic_potion_desc, MonsterDb.MONSTER_CLAY_GOLEM, 8, 4, 4, false));
        ItemRepository.addItem(ItemRepository.create(Item.Type.CONSUMABLE, 50, "highest_potion", C0380R.string.res_item_highest_potion, C0380R.drawable.item_highest_potion, C0380R.string.res_item_highest_potion_desc, MonsterDb.MONSTER_CARBUNCLE, 8, 6, 4, false));
        ItemRepository.addItem(ItemRepository.create(Item.Type.CONSUMABLE, 60, "highest_magic_potion", C0380R.string.res_item_highest_magic_potion, C0380R.drawable.item_highest_magic_potion, C0380R.string.res_item_highest_magic_potion_desc, 1000, 10, 6, 5, false));
        Item itemCreate = ItemRepository.create(Item.Type.WEAPON, 1010, "bear_hand", C0380R.string.res_item_bear_hand, C0380R.drawable.item_default, C0380R.string.res_item_bear_hand_desc, 0, 2, 1, 0, false);
        ItemRepository.addItem(itemCreate);
        ItemRepository.asEquippable(itemCreate, new boolean[]{true, true, true, true, true, true, true, true});
        ItemRepository.asWeapon(itemCreate, Item.WeaponType.MACE, 0, false, 0, false);
        Item itemCreate2 = ItemRepository.create(Item.Type.WEAPON, 1020, "club", C0380R.string.res_item_club, C0380R.drawable.item_club, C0380R.string.res_item_club_desc, 5, 4, 1, 1, false);
        ItemRepository.addItem(itemCreate2);
        ItemRepository.asEquippable(itemCreate2, new boolean[]{true, true, true, true, true, true, true, true});
        ItemRepository.asWeapon(itemCreate2, Item.WeaponType.MACE, 0, false, 0, false);
        Item itemCreate3 = ItemRepository.create(Item.Type.WEAPON, 1030, "sling", C0380R.string.res_item_sling, C0380R.drawable.item_sling, C0380R.string.res_item_sling_desc, 5, 4, 1, 0, false);
        ItemRepository.addItem(itemCreate3);
        ItemRepository.asEquippable(itemCreate3, new boolean[]{true, true, true, true, true, true, true, true});
        ItemRepository.asWeapon(itemCreate3, Item.WeaponType.MISSILE, 0, true, 0, true);
        Item itemCreate4 = ItemRepository.create(Item.Type.WEAPON, 1040, "sling_staff", C0380R.string.res_item_sling_staff, C0380R.drawable.item_sling_staff, C0380R.string.res_item_sling_staff_desc, 20, 4, 1, 1, false);
        ItemRepository.addItem(itemCreate4);
        ItemRepository.asEquippable(itemCreate4, new boolean[]{true, true, true, true, true, true, true, true});
        ItemRepository.asWeapon(itemCreate4, Item.WeaponType.MISSILE, 0, true, 0, true);
        Item itemCreate5 = ItemRepository.create(Item.Type.WEAPON, 1050, "staff", C0380R.string.res_item_staff, C0380R.drawable.item_staff, C0380R.string.res_item_staff_desc, 10, 6, 1, 1, false);
        ItemRepository.addItem(itemCreate5);
        ItemRepository.asEquippable(itemCreate5, new boolean[]{true, true, true, true, true, true, true, true});
        ItemRepository.asWeapon(itemCreate5, Item.WeaponType.MACE, 0, true, 0, false);
        Item itemCreate6 = ItemRepository.create(Item.Type.WEAPON, 1060, "dagger", C0380R.string.res_item_dagger, C0380R.drawable.item_dagger, C0380R.string.res_item_dagger_desc, 10, 4, 1, 0, false);
        ItemRepository.addItem(itemCreate6);
        ItemRepository.asEquippable(itemCreate6, new boolean[]{true, true, true, true, true, true, true, true});
        ItemRepository.asWeapon(itemCreate6, Item.WeaponType.SWORD, 0, false, 0, false);
        itemCreate6.addEffect(new Item.Effect(GameChar.Status.CRITICAL, 3));
        Item itemCreate7 = ItemRepository.create(Item.Type.WEAPON, 1070, "short_sword", C0380R.string.res_item_short_sword, C0380R.drawable.item_short_sword, C0380R.string.res_item_short_sword_desc, 20, 6, 1, 0, false);
        ItemRepository.addItem(itemCreate7);
        ItemRepository.asEquippable(itemCreate7, new boolean[]{true, true, true, false, true, false, true, true});
        ItemRepository.asWeapon(itemCreate7, Item.WeaponType.SWORD, 0, false, 0, false);
        itemCreate7.addEffect(new Item.Effect(GameChar.Status.CRITICAL, 1));
        Item itemCreate8 = ItemRepository.create(Item.Type.WEAPON, 1080, "gladius", C0380R.string.res_item_gladius, C0380R.drawable.item_gladius, C0380R.string.res_item_gladius_desc, 25, 6, 1, 0, false);
        ItemRepository.addItem(itemCreate8);
        ItemRepository.asEquippable(itemCreate8, new boolean[]{true, true, true, false, true, false, true, true});
        ItemRepository.asWeapon(itemCreate8, Item.WeaponType.SWORD, 0, false, 0, false);
        itemCreate8.addEffect(new Item.Effect(GameChar.Status.CRITICAL, 1));
        Item itemCreate9 = ItemRepository.create(Item.Type.WEAPON, 1090, "long_sword", C0380R.string.res_item_long_sword, C0380R.drawable.item_long_sword, C0380R.string.res_item_long_sword_desc, 80, 8, 1, 1, false);
        ItemRepository.addItem(itemCreate9);
        ItemRepository.asEquippable(itemCreate9, new boolean[]{true, true, true, false, true, false, true, true});
        ItemRepository.asWeapon(itemCreate9, Item.WeaponType.SWORD, 0, false, 0, false);
        itemCreate9.addEffect(new Item.Effect(GameChar.Status.CRITICAL, 1));
        Item itemCreate10 = ItemRepository.create(Item.Type.WEAPON, 1100, "giant_club", C0380R.string.res_item_giant_club, C0380R.drawable.item_giant_club, C0380R.string.res_item_giant_club_desc, 80, 8, 2, 4, false);
        ItemRepository.addItem(itemCreate10);
        ItemRepository.asEquippable(itemCreate10, new boolean[]{true, true, true, false, true, false, false, false});
        ItemRepository.asWeapon(itemCreate10, Item.WeaponType.MACE, 0, true, 0, false);
        Item itemCreate11 = ItemRepository.create(Item.Type.WEAPON, 1110, "war_hammer", C0380R.string.res_item_war_hammer, C0380R.drawable.item_war_hammer, C0380R.string.res_item_war_hammer_desc, 90, 3, 1, 4, false);
        ItemRepository.addItem(itemCreate11);
        ItemRepository.asEquippable(itemCreate11, new boolean[]{true, true, true, false, true, false, false, false});
        ItemRepository.asWeapon(itemCreate11, Item.WeaponType.MACE, 0, false, 0, false);
        itemCreate11.addEffect(new Item.Effect(GameChar.Attribute.AGI, -1));
        Item itemCreate12 = ItemRepository.create(Item.Type.WEAPON, 1120, "mace", C0380R.string.res_item_mace, C0380R.drawable.item_mace, C0380R.string.res_item_mace_desc, 90, 4, 1, 3, false);
        ItemRepository.addItem(itemCreate12);
        ItemRepository.asEquippable(itemCreate12, new boolean[]{true, true, true, false, true, true, true, true});
        ItemRepository.asWeapon(itemCreate12, Item.WeaponType.MACE, 0, false, 0, false);
        Item itemCreate13 = ItemRepository.create(Item.Type.WEAPON, 1130, "hand_axe", C0380R.string.res_item_hand_axe, C0380R.drawable.item_hand_axe, C0380R.string.res_item_hand_axe_desc, 100, 6, 1, 2, false);
        ItemRepository.addItem(itemCreate13);
        ItemRepository.asEquippable(itemCreate13, new boolean[]{true, true, true, false, true, true, true, true});
        ItemRepository.asWeapon(itemCreate13, Item.WeaponType.MACE, 0, false, 0, false);
        Item itemCreate14 = ItemRepository.create(Item.Type.WEAPON, 1140, "spear", C0380R.string.res_item_spear, C0380R.drawable.item_spear, C0380R.string.res_item_spear_desc, MonsterDb.MONSTER_STIRGE, 12, 1, 0, false);
        ItemRepository.addItem(itemCreate14);
        ItemRepository.asEquippable(itemCreate14, new boolean[]{true, true, true, false, true, false, true, true});
        ItemRepository.asWeapon(itemCreate14, Item.WeaponType.SPEAR, 0, false, 0, false);
        itemCreate14.addEffect(new Item.Effect(GameChar.Status.CRITICAL, 1));
        itemCreate14.addEffect(new Item.Effect(GameChar.Status.FUMBLE, 1));
        Item itemCreate15 = ItemRepository.create(Item.Type.WEAPON, 1150, "trident", C0380R.string.res_item_trident, C0380R.drawable.item_trident, C0380R.string.res_item_trident_desc, 200, 20, 1, 0, false);
        ItemRepository.addItem(itemCreate15);
        ItemRepository.asEquippable(itemCreate15, new boolean[]{true, true, false, false, true, false, true, false});
        ItemRepository.asWeapon(itemCreate15, Item.WeaponType.SPEAR, 0, true, 0, false);
        itemCreate15.addEffect(new Item.Effect(GameChar.Status.FUMBLE, 2));
        Item itemCreate16 = ItemRepository.create(Item.Type.WEAPON, 1160, "falchion", C0380R.string.res_item_falchion, C0380R.drawable.item_falchion, C0380R.string.res_item_falchion_desc, MonsterDb.MONSTER_STIRGE, 10, 1, 0, false);
        ItemRepository.addItem(itemCreate16);
        ItemRepository.asEquippable(itemCreate16, new boolean[]{true, true, true, false, true, false, true, true});
        ItemRepository.asWeapon(itemCreate16, Item.WeaponType.SWORD, 0, false, 0, false);
        Item itemCreate17 = ItemRepository.create(Item.Type.WEAPON, 1170, "battle_axe", C0380R.string.res_item_battle_axe, C0380R.drawable.item_battle_axe, C0380R.string.res_item_battle_axe_desc, 125, 10, 1, 3, false);
        ItemRepository.addItem(itemCreate17);
        ItemRepository.asEquippable(itemCreate17, new boolean[]{true, true, false, false, true, false, true, false});
        ItemRepository.asWeapon(itemCreate17, Item.WeaponType.MACE, 0, true, 1, false);
        itemCreate17.addEffect(new Item.Effect(GameChar.Status.FUMBLE, 1));
        itemCreate17.addEffect(new Item.Effect(GameChar.Attribute.AGI, -2));
        Item itemCreate18 = ItemRepository.create(Item.Type.WEAPON, 1180, "rapier", C0380R.string.res_item_rapier, C0380R.drawable.item_rapier, C0380R.string.res_item_rapier_desc, MonsterDb.MONSTER_GRAY_OOZE, 8, 1, 0, false);
        ItemRepository.addItem(itemCreate18);
        ItemRepository.asEquippable(itemCreate18, new boolean[]{true, true, true, false, true, false, true, true});
        ItemRepository.asWeapon(itemCreate18, Item.WeaponType.SWORD, 0, false, 0, false);
        itemCreate18.addEffect(new Item.Effect(GameChar.Status.CRITICAL, 3));
        Item itemCreate19 = ItemRepository.create(Item.Type.WEAPON, 1190, "great_sword", C0380R.string.res_item_great_sword, C0380R.drawable.item_great_sword, C0380R.string.res_item_great_sword_desc, MonsterDb.MONSTER_DRAGON_FLY, 10, 1, 2, false);
        ItemRepository.addItem(itemCreate19);
        ItemRepository.asEquippable(itemCreate19, new boolean[]{true, true, false, false, true, false, true, false});
        ItemRepository.asWeapon(itemCreate19, Item.WeaponType.SWORD, 0, true, 1, false);
        itemCreate19.addEffect(new Item.Effect(GameChar.Status.CRITICAL, 1));
        itemCreate19.addEffect(new Item.Effect(GameChar.Status.FUMBLE, 1));
        itemCreate19.addEffect(new Item.Effect(GameChar.Attribute.AGI, -1));
        Item itemCreate20 = ItemRepository.create(Item.Type.WEAPON, 1200, "short_bow", C0380R.string.res_item_short_bow, C0380R.drawable.item_short_bow, C0380R.string.res_item_short_bow_desc, MonsterDb.MONSTER_GHOUL, 6, 1, 0, false);
        ItemRepository.addItem(itemCreate20);
        ItemRepository.asEquippable(itemCreate20, new boolean[]{true, true, true, false, true, true, true, true});
        ItemRepository.asWeapon(itemCreate20, Item.WeaponType.MISSILE, 0, true, 0, true);
        Item itemCreate21 = ItemRepository.create(Item.Type.WEAPON, 1210, "long_bow", C0380R.string.res_item_long_bow, C0380R.drawable.item_long_bow, C0380R.string.res_item_long_bow_desc, 400, 8, 1, 0, false);
        ItemRepository.addItem(itemCreate21);
        ItemRepository.asEquippable(itemCreate21, new boolean[]{true, true, true, false, true, false, true, true});
        ItemRepository.asWeapon(itemCreate21, Item.WeaponType.MISSILE, 0, true, 0, true);
        Item itemCreate22 = ItemRepository.create(Item.Type.WEAPON, 1220, "composite_bow", C0380R.string.res_item_composite_bow, C0380R.drawable.item_composite_bow, C0380R.string.res_item_composite_bow_desc, 800, 10, 1, 0, false);
        ItemRepository.addItem(itemCreate22);
        ItemRepository.asEquippable(itemCreate22, new boolean[]{true, true, true, false, true, false, true, true});
        ItemRepository.asWeapon(itemCreate22, Item.WeaponType.MISSILE, 0, true, 0, true);
        Item itemCreate23 = ItemRepository.create(Item.Type.WEAPON, 1230, "halbard", C0380R.string.res_item_halbard, C0380R.drawable.item_halbard, C0380R.string.res_item_halbard_desc, MonsterDb.MONSTER_CONSTRICTOR, 6, 2, 1, false);
        ItemRepository.addItem(itemCreate23);
        ItemRepository.asEquippable(itemCreate23, new boolean[]{true, true, false, false, true, false, false, false});
        ItemRepository.asWeapon(itemCreate23, Item.WeaponType.SPEAR, 0, true, 2, false);
        itemCreate23.addEffect(new Item.Effect(GameChar.Status.CRITICAL, 1));
        itemCreate23.addEffect(new Item.Effect(GameChar.Status.FUMBLE, 1));
        itemCreate23.addEffect(new Item.Effect(GameChar.Attribute.AGI, -1));
        Item itemCreate24 = ItemRepository.create(Item.Type.WEAPON, 1240, "ninja_katana", C0380R.string.res_item_ninja_katana, C0380R.drawable.item_ninja_katana, C0380R.string.res_item_ninja_katana_desc, 400, 6, 1, 0, false);
        ItemRepository.addItem(itemCreate24);
        ItemRepository.asEquippable(itemCreate24, new boolean[]{true, true, true, false, true, false, true, true});
        ItemRepository.asWeapon(itemCreate24, Item.WeaponType.SWORD, 0, false, 0, false);
        itemCreate24.addEffect(new Item.Effect(GameChar.Status.CRITICAL, 5));
        Item itemCreate25 = ItemRepository.create(Item.Type.WEAPON, 1250, "samurai_blade", C0380R.string.res_item_samurai_blade, C0380R.drawable.item_samurai_blade, C0380R.string.res_item_samurai_blade_desc, MonsterDb.MONSTER_GHOST, 8, 1, 1, false);
        ItemRepository.addItem(itemCreate25);
        ItemRepository.asEquippable(itemCreate25, new boolean[]{true, true, true, false, true, false, true, true});
        ItemRepository.asWeapon(itemCreate25, Item.WeaponType.SWORD, 0, false, 0, false);
        itemCreate25.addEffect(new Item.Effect(GameChar.Status.CRITICAL, 2));
        Item itemCreate26 = ItemRepository.create(Item.Type.WEAPON, 1260, "claymore", C0380R.string.res_item_claymore, C0380R.drawable.item_claymore, C0380R.string.res_item_claymore_desc, MonsterDb.MONSTER_GHOST, 12, 1, 0, false);
        ItemRepository.addItem(itemCreate26);
        ItemRepository.asEquippable(itemCreate26, new boolean[]{true, true, false, false, true, false, true, false});
        ItemRepository.asWeapon(itemCreate26, Item.WeaponType.SWORD, 0, true, 1, false);
        itemCreate26.addEffect(new Item.Effect(GameChar.Status.CRITICAL, 2));
        itemCreate26.addEffect(new Item.Effect(GameChar.Status.FUMBLE, 1));
        itemCreate26.addEffect(new Item.Effect(GameChar.Attribute.AGI, -1));
        Item itemCreate27 = ItemRepository.create(Item.Type.WEAPON, 1270, "naginata", C0380R.string.res_item_naginata, C0380R.drawable.item_naginata, C0380R.string.res_item_naginata_desc, MonsterDb.MONSTER_OGRE, 8, 2, 0, false);
        ItemRepository.addItem(itemCreate27);
        ItemRepository.asEquippable(itemCreate27, new boolean[]{true, true, true, false, true, true, true, true});
        ItemRepository.asWeapon(itemCreate27, Item.WeaponType.SWORD, 0, true, 1, false);
        itemCreate27.addEffect(new Item.Effect(GameChar.Status.CRITICAL, 1));
        itemCreate27.addEffect(new Item.Effect(GameChar.Attribute.AGI, -1));
        Item itemCreate28 = ItemRepository.create(Item.Type.WEAPON, 1280, "excalibur", C0380R.string.res_item_excalibur, C0380R.drawable.item_excalibur, C0380R.string.res_item_excalibur_desc, 800, 10, 1, 1, true);
        ItemRepository.addItem(itemCreate28);
        ItemRepository.asEquippable(itemCreate28, new boolean[]{true, true, false, false, true, false, true, true});
        ItemRepository.asWeapon(itemCreate28, Item.WeaponType.SWORD, 4, false, 0, false);
        itemCreate28.addEffect(new Item.Effect(GameChar.Status.CRITICAL, 1));
        Item itemCreate29 = ItemRepository.create(Item.Type.WEAPON, 1290, "amanomurakumo", C0380R.string.res_item_amanomurakumo, C0380R.drawable.item_amanomurakumo, C0380R.string.res_item_amanomurakumo_desc, 800, 12, 1, 0, true);
        ItemRepository.addItem(itemCreate29);
        ItemRepository.asEquippable(itemCreate29, new boolean[]{true, true, true, false, true, false, true, true});
        ItemRepository.asWeapon(itemCreate29, Item.WeaponType.SWORD, 3, false, 0, false);
        itemCreate29.addEffect(new Item.Effect(GameChar.Status.CRITICAL, 1));
        Item itemCreate30 = ItemRepository.create(Item.Type.WEAPON, 1300, "orc_slayer", C0380R.string.res_item_orc_slayer, C0380R.drawable.item_orc_slayer, C0380R.string.res_item_orc_slayer_desc, 1000, 8, 1, 1, true);
        ItemRepository.addItem(itemCreate30);
        ItemRepository.asEquippable(itemCreate30, new boolean[]{true, true, true, false, true, true, true, true});
        ItemRepository.asWeapon(itemCreate30, Item.WeaponType.SWORD, 3, false, 0, false);
        itemCreate30.addEffect(new Item.Effect(GameChar.Status.CRITICAL, 2));
        Item itemCreate31 = ItemRepository.create(Item.Type.WEAPON, 1310, "undead_slayer", C0380R.string.res_item_undead_slayer, C0380R.drawable.item_undead_slayer, C0380R.string.res_item_undead_slayer_desc, 2000, 6, 1, 0, true);
        ItemRepository.addItem(itemCreate31);
        ItemRepository.asEquippable(itemCreate31, new boolean[]{true, true, true, false, true, true, true, true});
        ItemRepository.asWeapon(itemCreate31, Item.WeaponType.SWORD, 0, false, 0, false);
        itemCreate31.addEffect(new Item.Effect(GameChar.Status.CRITICAL, 1));
        Item itemCreate32 = ItemRepository.create(Item.Type.WEAPON, 1320, "terminus_est", C0380R.string.res_item_terminus_est, C0380R.drawable.item_terminus_est, C0380R.string.res_item_terminus_est_desc, 2800, 12, 1, 0, true);
        ItemRepository.addItem(itemCreate32);
        ItemRepository.asEquippable(itemCreate32, new boolean[]{true, true, true, false, true, false, true, true});
        ItemRepository.asWeapon(itemCreate32, Item.WeaponType.SWORD, 2, false, 0, false);
        itemCreate32.addEffect(new Item.Effect(GameChar.Status.CRITICAL, 1));
        Item itemCreate33 = ItemRepository.create(Item.Type.WEAPON, 1330, "graywand", C0380R.string.res_item_graywand, C0380R.drawable.item_graywand, C0380R.string.res_item_graywand_desc, 3000, 10, 1, 1, true);
        ItemRepository.addItem(itemCreate33);
        ItemRepository.asEquippable(itemCreate33, new boolean[]{true, true, true, false, true, false, true, true});
        ItemRepository.asWeapon(itemCreate33, Item.WeaponType.SWORD, 2, false, 0, false);
        itemCreate33.addEffect(new Item.Effect(GameChar.Status.CRITICAL, 1));
        Item itemCreate34 = ItemRepository.create(Item.Type.WEAPON, 1340, "scalpel", C0380R.string.res_item_scalpel, C0380R.drawable.item_scalpel, C0380R.string.res_item_scalpel_desc, 3000, 10, 1, 0, true);
        ItemRepository.addItem(itemCreate34);
        ItemRepository.asEquippable(itemCreate34, new boolean[]{true, true, true, false, true, false, true, true});
        ItemRepository.asWeapon(itemCreate34, Item.WeaponType.SWORD, 2, false, 0, false);
        itemCreate34.addEffect(new Item.Effect(GameChar.Status.CRITICAL, 3));
        Item itemCreate35 = ItemRepository.create(Item.Type.WEAPON, 1350, "dragon_slayer", C0380R.string.res_item_dragon_slayer, C0380R.drawable.item_dragon_slayer, C0380R.string.res_item_dragon_slayer_desc, 4000, 5, 1, 3, true);
        ItemRepository.addItem(itemCreate35);
        ItemRepository.asEquippable(itemCreate35, new boolean[]{true, true, true, false, true, false, true, true});
        ItemRepository.asWeapon(itemCreate35, Item.WeaponType.SWORD, 1, false, 0, false);
        itemCreate35.addEffect(new Item.Effect(GameChar.Status.CRITICAL, 1));
        Item itemCreate36 = ItemRepository.create(Item.Type.WEAPON, 1360, "were_slayer", C0380R.string.res_item_were_slayer, C0380R.drawable.item_were_slayer, C0380R.string.res_item_were_slayer_desc, 4000, 8, 1, 1, true);
        ItemRepository.addItem(itemCreate36);
        ItemRepository.asEquippable(itemCreate36, new boolean[]{true, true, true, false, true, false, true, true});
        ItemRepository.asWeapon(itemCreate36, Item.WeaponType.SWORD, 1, false, 0, false);
        itemCreate36.addEffect(new Item.Effect(GameChar.Status.CRITICAL, 1));
        itemCreate36.addEffect(new Item.Effect(GameChar.Attribute.AGI, -1));
        Item itemCreate37 = ItemRepository.create(Item.Type.WEAPON, 1370, "ogre_killer", C0380R.string.res_item_ogre_killer, C0380R.drawable.item_ogre_killer, C0380R.string.res_item_ogre_killer_desc, 4800, 10, 1, 3, true);
        ItemRepository.addItem(itemCreate37);
        ItemRepository.asEquippable(itemCreate37, new boolean[]{true, true, false, false, true, false, false, false});
        ItemRepository.asWeapon(itemCreate37, Item.WeaponType.MACE, 2, true, 1, false);
        itemCreate37.addEffect(new Item.Effect(GameChar.Status.FUMBLE, 1));
        itemCreate37.addEffect(new Item.Effect(GameChar.Attribute.AGI, -1));
        Item itemCreate38 = ItemRepository.create(Item.Type.WEAPON, 1380, "anduril", C0380R.string.res_item_anduril, C0380R.drawable.item_anduril, C0380R.string.res_item_anduril_desc, 8000, 8, 1, 1, true);
        ItemRepository.addItem(itemCreate38);
        ItemRepository.asEquippable(itemCreate38, new boolean[]{true, true, true, false, true, false, true, true});
        ItemRepository.asWeapon(itemCreate38, Item.WeaponType.SWORD, 4, false, 0, false);
        itemCreate38.addEffect(new Item.Effect(GameChar.Status.CRITICAL, 1));
        Item itemCreate39 = ItemRepository.create(Item.Type.WEAPON, 1390, "glamdring", C0380R.string.res_item_glamdring, C0380R.drawable.item_glamdring, C0380R.string.res_item_glamdring_desc, 8000, 6, 1, 5, true);
        ItemRepository.addItem(itemCreate39);
        ItemRepository.asEquippable(itemCreate39, new boolean[]{true, true, true, true, true, true, true, true});
        ItemRepository.asWeapon(itemCreate39, Item.WeaponType.SWORD, 2, false, 0, false);
        itemCreate39.addEffect(new Item.Effect(GameChar.Status.CRITICAL, 1));
        Item itemCreate40 = ItemRepository.create(Item.Type.WEAPON, 1400, "grayswandir", C0380R.string.res_item_grayswandir, C0380R.drawable.item_grayswandir, C0380R.string.res_item_grayswandir_desc, 9000, 10, 1, 0, true);
        ItemRepository.addItem(itemCreate40);
        ItemRepository.asEquippable(itemCreate40, new boolean[]{true, true, true, false, true, false, true, true});
        ItemRepository.asWeapon(itemCreate40, Item.WeaponType.SWORD, 4, false, 0, false);
        itemCreate40.addEffect(new Item.Effect(GameChar.Status.CRITICAL, 3));
        Item itemCreate41 = ItemRepository.create(Item.Type.WEAPON, 1410, "mjolnir", C0380R.string.res_item_mjolnir, C0380R.drawable.item_mjolnir, C0380R.string.res_item_mjolnir_desc, 10000, 6, 1, 7, true);
        ItemRepository.addItem(itemCreate41);
        ItemRepository.asEquippable(itemCreate41, new boolean[]{true, true, false, false, true, false, false, false});
        ItemRepository.asWeapon(itemCreate41, Item.WeaponType.MACE, 3, false, 0, false);
        itemCreate41.addEffect(new Item.Effect(GameChar.Attribute.AGI, -1));
        Item itemCreate42 = ItemRepository.create(Item.Type.WEAPON, 1420, "mournblade", C0380R.string.res_item_mournblade, C0380R.drawable.item_mournblade, C0380R.string.res_item_mournblade_desc, 10000, 10, 1, 0, true);
        ItemRepository.addItem(itemCreate42);
        ItemRepository.asEquippable(itemCreate42, new boolean[]{true, true, false, false, true, false, true, true});
        ItemRepository.asWeapon(itemCreate42, Item.WeaponType.SWORD, 4, false, 0, false);
        itemCreate42.addEffect(new Item.Effect(GameChar.Status.CRITICAL, 1));
        Item itemCreate43 = ItemRepository.create(Item.Type.WEAPON, 1430, "durandal", C0380R.string.res_item_durandal, C0380R.drawable.item_durandal, C0380R.string.res_item_durandal_desc, 10000, 8, 1, 2, true);
        ItemRepository.addItem(itemCreate43);
        ItemRepository.asEquippable(itemCreate43, new boolean[]{true, true, false, false, true, false, true, false});
        ItemRepository.asWeapon(itemCreate43, Item.WeaponType.SWORD, 3, false, 0, false);
        itemCreate43.addEffect(new Item.Effect(GameChar.Status.CRITICAL, 1));
        Item itemCreate44 = ItemRepository.create(Item.Type.WEAPON, 1440, "rhongomiant", C0380R.string.res_item_rhongomiant, C0380R.drawable.item_rhongomiant, C0380R.string.res_item_rhongomiant_desc, 10000, 10, 2, 0, true);
        ItemRepository.addItem(itemCreate44);
        ItemRepository.asEquippable(itemCreate44, new boolean[]{true, true, true, false, true, false, true, false});
        ItemRepository.asWeapon(itemCreate44, Item.WeaponType.SPEAR, 3, true, 1, false);
        itemCreate44.addEffect(new Item.Effect(GameChar.Status.CRITICAL, 1));
        itemCreate44.addEffect(new Item.Effect(GameChar.Attribute.AGI, -1));
        Item itemCreate45 = ItemRepository.create(Item.Type.WEAPON, 1450, "traitor", C0380R.string.res_item_traitor, C0380R.drawable.item_traitor, C0380R.string.res_item_traitor_desc, 10000, 8, 1, 1, true);
        ItemRepository.addItem(itemCreate45);
        ItemRepository.asEquippable(itemCreate45, new boolean[]{true, true, true, false, true, false, true, true});
        ItemRepository.asWeapon(itemCreate45, Item.WeaponType.SWORD, 4, false, 0, false);
        itemCreate45.addEffect(new Item.Effect(GameChar.Status.CRITICAL, 1));
        Item itemCreate46 = ItemRepository.create(Item.Type.WEAPON, 1460, "gram", C0380R.string.res_item_gram, C0380R.drawable.item_gram, C0380R.string.res_item_gram_desc, 12000, 12, 1, 2, true);
        ItemRepository.addItem(itemCreate46);
        ItemRepository.asEquippable(itemCreate46, new boolean[]{true, true, false, false, true, false, true, false});
        ItemRepository.asWeapon(itemCreate46, Item.WeaponType.SWORD, 3, true, 2, false);
        itemCreate46.addEffect(new Item.Effect(GameChar.Status.CRITICAL, 1));
        Item itemCreate47 = ItemRepository.create(Item.Type.WEAPON, 1470, "laevateinn", C0380R.string.res_item_laevateinn, C0380R.drawable.item_laevateinn, C0380R.string.res_item_laevateinn_desc, 14000, 12, 1, 3, true);
        ItemRepository.addItem(itemCreate47);
        ItemRepository.asEquippable(itemCreate47, new boolean[]{true, true, false, false, true, false, true, false});
        ItemRepository.asWeapon(itemCreate47, Item.WeaponType.SWORD, 5, true, 2, false);
        itemCreate47.addEffect(new Item.Effect(GameChar.Status.CRITICAL, 1));
        Item itemCreate48 = ItemRepository.create(Item.Type.WEAPON, 1480, "muramasa_blade", C0380R.string.res_item_muramasa_blade, C0380R.drawable.item_muramasa_blade, C0380R.string.res_item_muramasa_blade_desc, 14000, 10, 1, 1, true);
        ItemRepository.addItem(itemCreate48);
        ItemRepository.asEquippable(itemCreate48, new boolean[]{true, true, true, false, true, false, true, true});
        ItemRepository.asWeapon(itemCreate48, Item.WeaponType.SWORD, 5, false, 0, false);
        itemCreate48.addEffect(new Item.Effect(GameChar.Status.CRITICAL, 1));
        itemCreate48.addEffect(new Item.Effect(GameChar.Attribute.AGI, 1));
        Item itemCreate49 = ItemRepository.create(Item.Type.WEAPON, 1490, "gungnir", C0380R.string.res_item_gungnir, C0380R.drawable.item_gungnir, C0380R.string.res_item_gungnir_desc, 8000, 12, 1, 0, true);
        ItemRepository.addItem(itemCreate49);
        ItemRepository.asEquippable(itemCreate49, new boolean[]{true, true, false, false, true, false, true, false});
        ItemRepository.asWeapon(itemCreate49, Item.WeaponType.SPEAR, 4, false, 0, false);
        itemCreate49.addEffect(new Item.Effect(GameChar.Status.CRITICAL, 1));
        itemCreate49.addEffect(new Item.Effect(GameChar.Attribute.AGI, -1));
        Item itemCreate50 = ItemRepository.create(Item.Type.WEAPON, 1500, "gaebolg", C0380R.string.res_item_gaebolg, C0380R.drawable.item_gaebolg, C0380R.string.res_item_gaebolg_desc, 10000, 20, 1, 0, true);
        ItemRepository.addItem(itemCreate50);
        ItemRepository.asEquippable(itemCreate50, new boolean[]{true, true, false, false, true, false, true, false});
        ItemRepository.asWeapon(itemCreate50, Item.WeaponType.SPEAR, 4, true, 1, false);
        itemCreate50.addEffect(new Item.Effect(GameChar.Status.CRITICAL, 1));
        itemCreate50.addEffect(new Item.Effect(GameChar.Attribute.AGI, -1));
        Item itemCreate51 = ItemRepository.create(Item.Type.WEAPON, 1510, "bow_of_shekinah", C0380R.string.res_item_bow_of_shekinah, C0380R.drawable.item_bow_of_shekinah, C0380R.string.res_item_bow_of_shekinah_desc, 10000, 8, 1, 1, true);
        ItemRepository.addItem(itemCreate51);
        ItemRepository.asEquippable(itemCreate51, new boolean[]{false, true, true, false, true, true, false, true});
        ItemRepository.asWeapon(itemCreate51, Item.WeaponType.MISSILE, 3, true, 0, true);
        itemCreate51.addEffect(new Item.Effect(GameChar.Status.CRITICAL, 1));
        Item itemCreate52 = ItemRepository.create(Item.Type.WEAPON, 1520, "raijodo", C0380R.string.res_item_raijodo, C0380R.drawable.item_raijodo, C0380R.string.res_item_raijodo_desc, 8000, 10, 1, 1, true);
        ItemRepository.addItem(itemCreate52);
        ItemRepository.asEquippable(itemCreate52, new boolean[]{true, true, false, false, true, false, true, true});
        ItemRepository.asWeapon(itemCreate52, Item.WeaponType.MISSILE, 3, true, 0, true);
        itemCreate52.addEffect(new Item.Effect(GameChar.Status.CRITICAL, 1));
        Item itemCreate53 = ItemRepository.create(Item.Type.WEAPON, 1530, "elven_bow", C0380R.string.res_item_elven_bow, C0380R.drawable.item_elven_bow, C0380R.string.res_item_elven_bow_desc, 4000, 8, 1, 1, true);
        ItemRepository.addItem(itemCreate53);
        ItemRepository.asEquippable(itemCreate53, new boolean[]{false, false, true, true, false, true, false, false});
        ItemRepository.asWeapon(itemCreate53, Item.WeaponType.MISSILE, 2, true, 0, true);
        itemCreate53.addEffect(new Item.Effect(GameChar.Status.CRITICAL, 1));
        Item itemCreate54 = ItemRepository.create(Item.Type.WEAPON, 1540, "dagger_of_thieves", C0380R.string.res_item_dagger_of_thieves, C0380R.drawable.item_dagger_of_thieves, C0380R.string.res_item_dagger_of_thieves_desc, 8000, 6, 1, 1, true);
        ItemRepository.addItem(itemCreate54);
        ItemRepository.asEquippable(itemCreate54, new boolean[]{false, true, false, false, false, false, false, true});
        ItemRepository.asWeapon(itemCreate54, Item.WeaponType.SWORD, 4, false, 0, false);
        itemCreate54.addEffect(new Item.Effect(GameChar.Status.CRITICAL, 2));
        itemCreate54.addEffect(new Item.Effect(GameChar.Attribute.AGI, 1));
        Item itemCreate55 = ItemRepository.create(Item.Type.WEAPON, 1550, "magic_staff", C0380R.string.res_item_magic_staff, C0380R.drawable.item_magic_staff, C0380R.string.res_item_magic_staff_desc, MonsterDb.MONSTER_GHOUL, 3, 1, 1, false);
        ItemRepository.addItem(itemCreate55);
        ItemRepository.asEquippable(itemCreate55, new boolean[]{false, false, true, true, false, true, false, false});
        ItemRepository.asWeapon(itemCreate55, Item.WeaponType.MACE, 0, false, 0, false);
        itemCreate55.addEffect(new Item.Effect(GameChar.Status.FUMBLE, 1));
        Item itemCreate56 = ItemRepository.create(Item.Type.WEAPON, 1560, "sorcerers_staff", C0380R.string.res_item_sorcerers_staff, C0380R.drawable.item_sorcerers_staff, C0380R.string.res_item_sorcerers_staff_desc, 3000, 3, 1, 1, false);
        ItemRepository.addItem(itemCreate56);
        ItemRepository.asEquippable(itemCreate56, new boolean[]{false, false, false, true, false, true, false, false});
        ItemRepository.asWeapon(itemCreate56, Item.WeaponType.MACE, 0, false, 0, false);
        itemCreate56.addEffect(new Item.Effect(GameChar.Status.FUMBLE, 1));
        Item itemCreate57 = ItemRepository.create(Item.Type.WEAPON, 1570, "eriril", C0380R.string.res_item_eriril, C0380R.drawable.item_eriril, C0380R.string.res_item_eriril_desc, 12000, 6, 1, 1, true);
        ItemRepository.addItem(itemCreate57);
        ItemRepository.asEquippable(itemCreate57, new boolean[]{false, false, false, true, false, false, false, false});
        ItemRepository.asWeapon(itemCreate57, Item.WeaponType.MACE, 1, true, 1, false);
        itemCreate57.addEffect(new Item.Effect(GameChar.Status.FUMBLE, 1));
        Item itemCreate58 = ItemRepository.create(Item.Type.ARMOR, ITEM_ROBE, "robe", C0380R.string.res_item_robe, C0380R.drawable.item_robe, C0380R.string.res_item_robe_desc, 5, 0, 0, 0, false);
        ItemRepository.addItem(itemCreate58);
        ItemRepository.asEquippable(itemCreate58, new boolean[]{true, true, true, true, true, true, true, true});
        ItemRepository.asArmor(itemCreate58, 0);
        Item itemCreate59 = ItemRepository.create(Item.Type.ARMOR, ITEM_LEATHER_ARMOR, "leather_armor", C0380R.string.res_item_leather_armor, C0380R.drawable.item_leather_armor, C0380R.string.res_item_leather_armor_desc, 40, 0, 0, 1, false);
        ItemRepository.addItem(itemCreate59);
        ItemRepository.asEquippable(itemCreate59, new boolean[]{true, true, true, true, true, true, true, true});
        ItemRepository.asArmor(itemCreate59, 0);
        Item itemCreate60 = ItemRepository.create(Item.Type.ARMOR, ITEM_RING_MAIL, "ring_mail", C0380R.string.res_item_ring_mail, C0380R.drawable.item_ring_mail, C0380R.string.res_item_ring_mail_desc, 100, 0, 0, 3, false);
        ItemRepository.addItem(itemCreate60);
        ItemRepository.asEquippable(itemCreate60, new boolean[]{true, false, true, false, true, true, true, false});
        ItemRepository.asArmor(itemCreate60, 0);
        itemCreate60.addEffect(new Item.Effect(GameChar.Attribute.AGI, -1));
        Item itemCreate61 = ItemRepository.create(Item.Type.ARMOR, ITEM_CHAIN_MAIL, "chain_mail", C0380R.string.res_item_chain_mail, C0380R.drawable.item_chain_mail, C0380R.string.res_item_chain_mail_desc, MonsterDb.MONSTER_GHOUL, 0, 0, 3, false);
        ItemRepository.addItem(itemCreate61);
        ItemRepository.asEquippable(itemCreate61, new boolean[]{true, false, true, false, true, true, true, false});
        ItemRepository.asArmor(itemCreate61, 0);
        Item itemCreate62 = ItemRepository.create(Item.Type.ARMOR, ITEM_BREAST_PLATE, "breast_plate", C0380R.string.res_item_breast_plate, C0380R.drawable.item_breast_plate, C0380R.string.res_item_breast_plate_desc, 250, 0, 0, 3, false);
        ItemRepository.addItem(itemCreate62);
        ItemRepository.asEquippable(itemCreate62, new boolean[]{true, true, true, false, true, false, true, true});
        ItemRepository.asArmor(itemCreate62, 0);
        Item itemCreate63 = ItemRepository.create(Item.Type.ARMOR, ITEM_PLATE_ARMOR, "plate_armor", C0380R.string.res_item_plate_armor, C0380R.drawable.item_plate_armor, C0380R.string.res_item_plate_armor_desc, 400, 0, 0, 5, false);
        ItemRepository.addItem(itemCreate63);
        ItemRepository.asEquippable(itemCreate63, new boolean[]{true, false, true, false, true, false, true, false});
        ItemRepository.asArmor(itemCreate63, 0);
        itemCreate63.addEffect(new Item.Effect(GameChar.Attribute.AGI, -2));
        Item itemCreate64 = ItemRepository.create(Item.Type.ARMOR, ITEM_LAMELLAR, "lamellar", C0380R.string.res_item_lamellar, C0380R.drawable.item_lamellar, C0380R.string.res_item_lamellar_desc, 800, 0, 0, 4, false);
        ItemRepository.addItem(itemCreate64);
        ItemRepository.asEquippable(itemCreate64, new boolean[]{true, false, true, false, true, false, true, false});
        ItemRepository.asArmor(itemCreate64, 0);
        itemCreate64.addEffect(new Item.Effect(GameChar.Attribute.AGI, -1));
        Item itemCreate65 = ItemRepository.create(Item.Type.ARMOR, ITEM_MITHRIL_CHAIN, "mithril_chain", C0380R.string.res_item_mithril_chain, C0380R.drawable.item_mithril_chain, C0380R.string.res_item_mithril_chain_desc, 1200, 0, 0, 4, true);
        ItemRepository.addItem(itemCreate65);
        ItemRepository.asEquippable(itemCreate65, new boolean[]{true, false, true, false, true, true, true, false});
        ItemRepository.asArmor(itemCreate65, 2);
        Item itemCreate66 = ItemRepository.create(Item.Type.ARMOR, ITEM_DRAGON_SCALE, "dragon_scale", C0380R.string.res_item_dragon_scale, C0380R.drawable.item_dragon_scale, C0380R.string.res_item_dragon_scale_desc, 10000, 0, 0, 2, true);
        ItemRepository.addItem(itemCreate66);
        ItemRepository.asEquippable(itemCreate66, new boolean[]{true, false, true, false, true, false, true, false});
        ItemRepository.asArmor(itemCreate66, 3);
        itemCreate66.addEffect(new Item.Effect(GameChar.Attribute.AGI, -1));
        Item itemCreate67 = ItemRepository.create(Item.Type.ARMOR, ITEM_BATTLE_DRESS, "battle_dress", C0380R.string.res_item_battle_dress, C0380R.drawable.item_battle_dress, C0380R.string.res_item_battle_dress_desc, 12000, 0, 0, 8, true);
        ItemRepository.addItem(itemCreate67);
        ItemRepository.asEquippable(itemCreate67, new boolean[]{true, true, true, false, true, false, true, true});
        ItemRepository.asArmor(itemCreate67, 0);
        Item itemCreate68 = ItemRepository.create(Item.Type.ARMOR, ITEM_GARB_OF_LORDS, "garb_of_lords", C0380R.string.res_item_garb_of_lords, C0380R.drawable.item_garb_of_lords, C0380R.string.res_item_garb_of_lords_desc, 12000, 0, 0, 6, true);
        ItemRepository.addItem(itemCreate68);
        ItemRepository.asEquippable(itemCreate68, new boolean[]{true, false, false, false, true, false, false, false});
        ItemRepository.asArmor(itemCreate68, 2);
        Item itemCreate69 = ItemRepository.create(Item.Type.SHIELD, ITEM_BUCKLER, "buckler", C0380R.string.res_item_buckler, C0380R.drawable.item_buckler, C0380R.string.res_item_buckler_desc, 10, 0, 0, 1, false);
        ItemRepository.addItem(itemCreate69);
        ItemRepository.asEquippable(itemCreate69, new boolean[]{true, true, true, true, true, true, true, true});
        ItemRepository.asShield(itemCreate69, 0);
        Item itemCreate70 = ItemRepository.create(Item.Type.SHIELD, ITEM_SMALL_SHIELD, "small_shield", C0380R.string.res_item_small_shield, C0380R.drawable.item_small_shield, C0380R.string.res_item_small_shield_desc, 40, 0, 0, 2, false);
        ItemRepository.addItem(itemCreate70);
        ItemRepository.asEquippable(itemCreate70, new boolean[]{true, true, true, false, true, true, true, true});
        ItemRepository.asShield(itemCreate70, 0);
        Item itemCreate71 = ItemRepository.create(Item.Type.SHIELD, ITEM_LARGE_SHIELD, "large_shield", C0380R.string.res_item_large_shield, C0380R.drawable.item_large_shield, C0380R.string.res_item_large_shield_desc, MonsterDb.MONSTER_STIRGE, 0, 0, 3, false);
        ItemRepository.addItem(itemCreate71);
        ItemRepository.asEquippable(itemCreate71, new boolean[]{true, true, true, false, true, false, true, false});
        ItemRepository.asShield(itemCreate71, 0);
        itemCreate71.addEffect(new Item.Effect(GameChar.Attribute.AGI, -1));
        Item itemCreate72 = ItemRepository.create(Item.Type.SHIELD, ITEM_TOWER_SHIELD, "tower_shield", C0380R.string.res_item_tower_shield, C0380R.drawable.item_tower_shield, C0380R.string.res_item_tower_shield_desc, 200, 0, 0, 4, false);
        ItemRepository.addItem(itemCreate72);
        ItemRepository.asEquippable(itemCreate72, new boolean[]{true, true, true, false, true, false, false, false});
        ItemRepository.asShield(itemCreate72, 0);
        itemCreate72.addEffect(new Item.Effect(GameChar.Attribute.AGI, -2));
        Item itemCreate73 = ItemRepository.create(Item.Type.SHIELD, ITEM_AIGIS, "aigis", C0380R.string.res_item_aigis, C0380R.drawable.item_aigis, C0380R.string.res_item_aigis_desc, 10000, 0, 0, 3, true);
        ItemRepository.addItem(itemCreate73);
        ItemRepository.asEquippable(itemCreate73, new boolean[]{true, true, true, false, true, false, true, false});
        ItemRepository.asShield(itemCreate73, 4);
        itemCreate73.addEffect(new Item.Effect(GameChar.Attribute.AGI, -1));
        Item itemCreate74 = ItemRepository.create(Item.Type.SHIELD, ITEM_PRYTWEN, "prytwen", C0380R.string.res_item_prytwen, C0380R.drawable.item_prytwen, C0380R.string.res_item_prytwen_desc, 10000, 0, 0, 2, true);
        ItemRepository.addItem(itemCreate74);
        ItemRepository.asEquippable(itemCreate74, new boolean[]{true, true, true, false, true, true, true, true});
        ItemRepository.asShield(itemCreate74, 4);
        Item itemCreate75 = ItemRepository.create(Item.Type.SHIELD, ITEM_LINK_SHIELD, "link_shield", C0380R.string.res_item_link_shield, C0380R.drawable.item_link_shield, C0380R.string.res_item_link_shield_desc, 4000, 0, 0, 2, true);
        ItemRepository.addItem(itemCreate75);
        ItemRepository.asEquippable(itemCreate75, new boolean[]{false, true, true, true, false, true, false, true});
        ItemRepository.asShield(itemCreate75, 2);
        Item itemCreate76 = ItemRepository.create(Item.Type.RING, ITEM_RING_OF_STR, "ring_of_str", C0380R.string.res_item_ring_of_str, C0380R.drawable.item_ring_ruby, C0380R.string.res_item_ring_of_str_desc, 800, 0, 0, 0, true);
        ItemRepository.addItem(itemCreate76);
        ItemRepository.asEquippable(itemCreate76, new boolean[]{true, true, true, true, true, true, true, true});
        Item itemCreate77 = ItemRepository.create(Item.Type.RING, ITEM_RING_OF_VIT, "ring_of_vit", C0380R.string.res_item_ring_of_vit, C0380R.drawable.item_ring_garnet, C0380R.string.res_item_ring_of_vit_desc, 800, 0, 0, 0, true);
        ItemRepository.addItem(itemCreate77);
        ItemRepository.asEquippable(itemCreate77, new boolean[]{true, true, true, true, true, true, true, true});
        Item itemCreate78 = ItemRepository.create(Item.Type.RING, ITEM_RING_OF_INT, "ring_of_int", C0380R.string.res_item_ring_of_int, C0380R.drawable.item_ring_sapphire, C0380R.string.res_item_ring_of_int_desc, 800, 0, 0, 0, true);
        ItemRepository.addItem(itemCreate78);
        ItemRepository.asEquippable(itemCreate78, new boolean[]{true, true, true, true, true, true, true, true});
        Item itemCreate79 = ItemRepository.create(Item.Type.RING, ITEM_RING_OF_AGI, "ring_of_agi", C0380R.string.res_item_ring_of_agi, C0380R.drawable.item_ring_emerald, C0380R.string.res_item_ring_of_agi_desc, 800, 0, 0, 0, true);
        ItemRepository.addItem(itemCreate79);
        ItemRepository.asEquippable(itemCreate79, new boolean[]{true, true, true, true, true, true, true, true});
        Item itemCreate80 = ItemRepository.create(Item.Type.RING, ITEM_RING_OF_STR2, "ring_of_str2", C0380R.string.res_item_ring_of_str2, C0380R.drawable.item_ring_ruby, C0380R.string.res_item_ring_of_str2_desc, 2000, 0, 0, 0, true);
        ItemRepository.addItem(itemCreate80);
        ItemRepository.asEquippable(itemCreate80, new boolean[]{true, true, true, true, true, true, true, true});
        Item itemCreate81 = ItemRepository.create(Item.Type.RING, ITEM_RING_OF_VIT2, "ring_of_vit2", C0380R.string.res_item_ring_of_vit2, C0380R.drawable.item_ring_garnet, C0380R.string.res_item_ring_of_vit2_desc, 2000, 0, 0, 0, true);
        ItemRepository.addItem(itemCreate81);
        ItemRepository.asEquippable(itemCreate81, new boolean[]{true, true, true, true, true, true, true, true});
        Item itemCreate82 = ItemRepository.create(Item.Type.RING, ITEM_RING_OF_INT2, "ring_of_int2", C0380R.string.res_item_ring_of_int2, C0380R.drawable.item_ring_sapphire, C0380R.string.res_item_ring_of_int2_desc, 2000, 0, 0, 0, true);
        ItemRepository.addItem(itemCreate82);
        ItemRepository.asEquippable(itemCreate82, new boolean[]{true, true, true, true, true, true, true, true});
        Item itemCreate83 = ItemRepository.create(Item.Type.RING, ITEM_RING_OF_AGI2, "ring_of_agi2", C0380R.string.res_item_ring_of_agi2, C0380R.drawable.item_ring_emerald, C0380R.string.res_item_ring_of_agi2_desc, 2000, 0, 0, 0, true);
        ItemRepository.addItem(itemCreate83);
        ItemRepository.asEquippable(itemCreate83, new boolean[]{true, true, true, true, true, true, true, true});
        Item itemCreate84 = ItemRepository.create(Item.Type.RING, ITEM_RING_OF_DEFENSE, "ring_of_defense", C0380R.string.res_item_ring_of_defense, C0380R.drawable.item_ring_gold, C0380R.string.res_item_ring_of_defense_desc, 2000, 0, 0, 0, true);
        ItemRepository.addItem(itemCreate84);
        ItemRepository.asEquippable(itemCreate84, new boolean[]{true, true, true, true, true, true, true, true});
        Item itemCreate85 = ItemRepository.create(Item.Type.RING, ITEM_RING_OF_HITTING, "ring_of_hitting", C0380R.string.res_item_ring_of_hitting, C0380R.drawable.item_ring_silver, C0380R.string.res_item_ring_of_hitting_desc, 2000, 0, 0, 0, true);
        ItemRepository.addItem(itemCreate85);
        ItemRepository.asEquippable(itemCreate85, new boolean[]{true, true, true, true, true, true, true, true});
        Item itemCreate86 = ItemRepository.create(Item.Type.RING, ITEM_RING_OF_DODGE, "ring_of_dodge", C0380R.string.res_item_ring_of_dodge, C0380R.drawable.item_ring_double, C0380R.string.res_item_ring_of_dodge_desc, 2500, 0, 0, 0, true);
        ItemRepository.addItem(itemCreate86);
        ItemRepository.asEquippable(itemCreate86, new boolean[]{true, true, true, true, true, true, true, true});
        Item itemCreate87 = ItemRepository.create(Item.Type.RING, ITEM_RING_OF_CRITICAL, "ring_of_critical", C0380R.string.res_item_ring_of_critical, C0380R.drawable.item_ring_jewels, C0380R.string.res_item_ring_of_critical_desc, 3000, 0, 0, 0, true);
        ItemRepository.addItem(itemCreate87);
        ItemRepository.asEquippable(itemCreate87, new boolean[]{true, true, true, true, true, true, true, true});
        ItemRepository.addItem(ItemRepository.create(Item.Type.OTHER, ITEM_RUSTED_KEY, "rusted_key", C0380R.string.res_item_rusted_key, C0380R.drawable.item_rusted_key, C0380R.string.res_item_rusted_key_desc, 10, 0, 0, 0, true));
        ItemRepository.addItem(ItemRepository.create(Item.Type.OTHER, ITEM_PURPLE_FLOWER, "purple_flower", C0380R.string.res_item_purple_flower, C0380R.drawable.item_purple_flower, C0380R.string.res_item_purple_flower_desc, 20, 0, 0, 0, true));
        ItemRepository.addItem(ItemRepository.create(Item.Type.OTHER, ITEM_SILVER_HANDLE, "silver_handle", C0380R.string.res_item_silver_handle, C0380R.drawable.item_silver_handle, C0380R.string.res_item_silver_handle_desc, 100, 0, 0, 0, true));
        ItemRepository.addItem(ItemRepository.create(Item.Type.OTHER, ITEM_PAPER_FOLDER, "paper_folder", C0380R.string.res_item_paper_folder, C0380R.drawable.item_paper_folder, C0380R.string.res_item_paper_folder_desc, 10, 0, 0, 0, true));
        ItemRepository.addItem(ItemRepository.create(Item.Type.OTHER, ITEM_SOUL_AMULET, "soul_amulet", C0380R.string.res_item_soul_amulet, C0380R.drawable.item_soul_amulet, C0380R.string.res_item_soul_amulet_desc, 200, 0, 0, 0, true));
        ItemRepository.addItem(ItemRepository.create(Item.Type.OTHER, ITEM_DEMON_AMULET, "demon_amulet", C0380R.string.res_item_demon_amulet, C0380R.drawable.item_demon_amulet, C0380R.string.res_item_demon_amulet_desc, 400, 0, 0, 0, true));
        ItemRepository.addItem(ItemRepository.create(Item.Type.OTHER, 5070, "kingdom_order", C0380R.string.res_item_kingdom_order, C0380R.drawable.item_kingdom_order, C0380R.string.res_item_kingdom_order_desc, 4000, 0, 0, 0, true));
        ItemRepository.addItem(ItemRepository.create(Item.Type.OTHER, ITEM_MEDAL_OF_LORDS, "medal_of_lords", C0380R.string.res_item_medal_of_lords, C0380R.drawable.item_medal_of_lords, C0380R.string.res_item_medal_of_lords_desc, 4000, 0, 0, 0, true));
        ItemRepository.addItem(ItemRepository.create(Item.Type.OTHER, ITEM_SECRET_SCROLL, "secret_scroll", C0380R.string.res_item_secret_scroll, C0380R.drawable.item_secret_scroll, C0380R.string.res_item_secret_scroll_desc, 4000, 0, 0, 0, true));
        ItemRepository.addItem(ItemRepository.create(Item.Type.OTHER, ITEM_ASTRO_BOOK, "astro_book", C0380R.string.res_item_astro_book, C0380R.drawable.item_astro_book, C0380R.string.res_item_astro_book_desc, 4000, 0, 0, 0, true));
        ItemRepository.addItem(ItemRepository.create(Item.Type.OTHER, ITEM_FIGHTER_SYMBOL, "fighter_symbol", C0380R.string.res_item_fighter_symbol, C0380R.drawable.item_fighter_symbol, C0380R.string.res_item_fighter_symbol_desc, 200, 0, 0, 0, true));
        ItemRepository.addItem(ItemRepository.create(Item.Type.OTHER, ITEM_THIEVES_GUILD, "thieves_guild", C0380R.string.res_item_thieves_guild, C0380R.drawable.item_thieves_guild, C0380R.string.res_item_thieves_guild_desc, 200, 0, 0, 0, true));
        ItemRepository.addItem(ItemRepository.create(Item.Type.OTHER, ITEM_HOLY_SYMBOL, "holy_symbol", C0380R.string.res_item_holy_symbol, C0380R.drawable.item_holy_symbol, C0380R.string.res_item_holy_symbol_desc, 200, 0, 0, 0, true));
        ItemRepository.addItem(ItemRepository.create(Item.Type.OTHER, ITEM_MAGIC_BOOK, "magic_book", C0380R.string.res_item_magic_book, C0380R.drawable.item_magic_book, C0380R.string.res_item_magic_book_desc, 200, 0, 0, 0, true));
        ItemRepository.addItem(ItemRepository.create(Item.Type.OTHER, ITEM_DWARVEN_ANVIL, "dwarven_anvil", C0380R.string.res_item_dwarven_anvil, C0380R.drawable.item_dwarven_anvil, C0380R.string.res_item_dwarven_anvil_desc, 2000, 0, 0, 0, true));
        ItemRepository.addItem(ItemRepository.create(Item.Type.OTHER, ITEM_SYNTHETIC_CATALYST, "synthetic_catalyst", C0380R.string.res_item_synthetic_catalyst, C0380R.drawable.item_synthetic_catalyst, C0380R.string.res_item_synthetic_catalyst_desc, 5000, 0, 0, 0, false));
        ItemRepository.addItem(ItemRepository.create(Item.Type.OTHER, ITEM_MONSTERS_JEWEL, "monsters_jewel", C0380R.string.res_item_monsters_jewel, C0380R.drawable.item_monsters_jewel, C0380R.string.res_item_monsters_jewel_desc, 3000, 0, 0, 0, true));
        ItemRepository.getItem(context, 10).addEffect(new Item.Effect(Item.Effect.Type.RESTORE_HP, GameChar.Attribute.VIT, 0));
        ItemRepository.getItem(context, 20).addEffect(new Item.Effect(Item.Effect.Type.RESTORE_MP, GameChar.Attribute.INT, 0));
        ItemRepository.getItem(context, 30).addEffect(new Item.Effect(Item.Effect.Type.RESTORE_HP, GameChar.Attribute.VIT, 0));
        ItemRepository.getItem(context, 40).addEffect(new Item.Effect(Item.Effect.Type.RESTORE_MP, GameChar.Attribute.INT, 0));
        ItemRepository.getItem(context, 50).addEffect(new Item.Effect(Item.Effect.Type.RESTORE_HP, GameChar.Attribute.VIT, 0));
        ItemRepository.getItem(context, 60).addEffect(new Item.Effect(Item.Effect.Type.RESTORE_MP, GameChar.Attribute.INT, 0));
        ItemRepository.getItem(context, 1300).addEffect(new Item.Effect(MonsterDb.MONSTER_ORC, 2));
        ItemRepository.getItem(context, 1300).addEffect(new Item.Effect(MonsterDb.MONSTER_HIGH_ORC, 2));
        ItemRepository.getItem(context, 1300).addEffect(new Item.Effect(GameChar.Attribute.STR, 2));
        ItemRepository.getItem(context, 1310).addEffect(new Item.Effect(Monster.MonsterType.UNDEAD, 2));
        ItemRepository.getItem(context, 1320).addEffect(new Item.Effect(GameChar.Status.DAMAGE, 1));
        ItemRepository.getItem(context, 1330).addEffect(new Item.Effect(GameChar.Status.DAMAGE, 2));
        ItemRepository.getItem(context, 1340).addEffect(new Item.Effect(GameChar.Status.DAMAGE, 2));
        ItemRepository.getItem(context, 1350).addEffect(new Item.Effect(Monster.MonsterType.DRAGON, 2));
        ItemRepository.getItem(context, 1360).addEffect(new Item.Effect(Monster.MonsterType.LYCANSLOPE, 2));
        ItemRepository.getItem(context, 1370).addEffect(new Item.Effect(MonsterDb.MONSTER_OGRE, 3));
        ItemRepository.getItem(context, 1380).addEffect(new Item.Effect(Monster.MonsterType.DEMON, 2));
        ItemRepository.getItem(context, 1380).addEffect(new Item.Effect(GameChar.Attribute.INT, 1));
        ItemRepository.getItem(context, 1390).addEffect(new Item.Effect(GameChar.Status.HIT_BONUS, 1));
        ItemRepository.getItem(context, 1390).addEffect(new Item.Effect(MonsterDb.MONSTER_ORC, 2));
        ItemRepository.getItem(context, 1390).addEffect(new Item.Effect(MonsterDb.MONSTER_HIGH_ORC, 2));
        ItemRepository.getItem(context, 1400).addEffect(new Item.Effect(Monster.MonsterType.CREATED, 2));
        ItemRepository.getItem(context, 1400).addEffect(new Item.Effect(Monster.MonsterType.UNDEAD, 2));
        ItemRepository.getItem(context, 1410).addEffect(new Item.Effect(Monster.MonsterType.ANIMAL, 2));
        ItemRepository.getItem(context, 1410).addEffect(new Item.Effect(Monster.MonsterType.GIANT, 2));
        ItemRepository.getItem(context, 1410).addEffect(new Item.Effect(GameChar.Status.HIT_BONUS, 1));
        ItemRepository.getItem(context, 1410).addEffect(new Item.Effect(GameChar.Attribute.STR, 1));
        ItemRepository.getItem(context, 1420).addEffect(new Item.Effect(Monster.MonsterType.DEMI_HUMAN, 2));
        ItemRepository.getItem(context, 1420).addEffect(new Item.Effect(GameChar.Attribute.STR, 1));
        ItemRepository.getItem(context, 1420).addEffect(new Item.Effect(GameChar.Attribute.VIT, 1));
        ItemRepository.getItem(context, 1430).addEffect(new Item.Effect(Monster.MonsterType.DRAGON, 3));
        ItemRepository.getItem(context, 1440).addEffect(new Item.Effect(Monster.MonsterType.DEMON, 2));
        ItemRepository.getItem(context, 1440).addEffect(new Item.Effect(Monster.MonsterType.UNDEAD, 2));
        ItemRepository.getItem(context, 1440).addEffect(new Item.Effect(GameChar.Attribute.INT, 1));
        ItemRepository.getItem(context, 1450).addEffect(new Item.Effect(Monster.MonsterType.HUMAN, 2));
        ItemRepository.getItem(context, 1450).addEffect(new Item.Effect(Monster.MonsterType.ANIMAL, 2));
        ItemRepository.getItem(context, 1450).addEffect(new Item.Effect(GameChar.Attribute.STR, 1));
        ItemRepository.getItem(context, 1450).addEffect(new Item.Effect(GameChar.Attribute.VIT, 1));
        ItemRepository.getItem(context, 1460).addEffect(new Item.Effect(Monster.MonsterType.DRAGON, 2));
        ItemRepository.getItem(context, 1490).addEffect(new Item.Effect(GameChar.Attribute.INT, 1));
        ItemRepository.getItem(context, 1490).addEffect(new Item.Effect(GameChar.Status.HIT_BONUS, 1));
        ItemRepository.getItem(context, 1500).addEffect(new Item.Effect(Monster.MonsterType.HUMAN, 2));
        ItemRepository.getItem(context, 1500).addEffect(new Item.Effect(GameChar.Status.HIT_BONUS, 1));
        ItemRepository.getItem(context, 1510).addEffect(new Item.Effect(Monster.MonsterType.UNDEAD, 2));
        ItemRepository.getItem(context, 1510).addEffect(new Item.Effect(Monster.MonsterType.DEMON, 2));
        ItemRepository.getItem(context, 1520).addEffect(new Item.Effect(Monster.MonsterType.ANIMAL, 2));
        ItemRepository.getItem(context, 1520).addEffect(new Item.Effect(Monster.MonsterType.DEMON, 2));
        ItemRepository.getItem(context, 1530).addEffect(new Item.Effect(GameChar.Attribute.INT, 1));
        ItemRepository.getItem(context, 1530).addEffect(new Item.Effect(Monster.MonsterType.CREATED, 2));
        ItemRepository.getItem(context, 1550).addEffect(new Item.Effect(GameChar.Status.MAGIC_BONUS, 1));
        ItemRepository.getItem(context, 1560).addEffect(new Item.Effect(GameChar.Status.MAGIC_BONUS, 2));
        ItemRepository.getItem(context, 1560).addEffect(new Item.Effect(GameChar.Status.MAGIC_DAMAGE_BONUS, 1));
        ItemRepository.getItem(context, 1570).addEffect(new Item.Effect(GameChar.Attribute.INT, 1));
        ItemRepository.getItem(context, 1570).addEffect(new Item.Effect(GameChar.Status.MAGIC_BONUS, 4));
        ItemRepository.getItem(context, 1570).addEffect(new Item.Effect(GameChar.Status.MAGIC_DAMAGE_BONUS, 3));
        ItemRepository.getItem(context, ITEM_MITHRIL_CHAIN).addEffect(new Item.Effect(GameChar.Attribute.INT, 1));
        ItemRepository.getItem(context, ITEM_BATTLE_DRESS).addEffect(new Item.Effect(GameChar.Attribute.STR, 1));
        ItemRepository.getItem(context, ITEM_BATTLE_DRESS).addEffect(new Item.Effect(GameChar.Attribute.VIT, 1));
        ItemRepository.getItem(context, ITEM_BATTLE_DRESS).addEffect(new Item.Effect(GameChar.Attribute.INT, -1));
        ItemRepository.getItem(context, ITEM_BATTLE_DRESS).addEffect(new Item.Effect(GameChar.Status.LIGHT_WEIGHT, 6));
        ItemRepository.getItem(context, ITEM_PRYTWEN).addEffect(new Item.Effect(GameChar.Attribute.INT, 1));
        ItemRepository.getItem(context, ITEM_LINK_SHIELD).addEffect(new Item.Effect(GameChar.Status.LIGHT_WEIGHT, 1));
        ItemRepository.getItem(context, ITEM_LINK_SHIELD).addEffect(new Item.Effect(GameChar.Status.ANTI_MAGIC_BONUS, 1));
        ItemRepository.getItem(context, ITEM_RING_OF_STR).addEffect(new Item.Effect(GameChar.Attribute.STR, 1));
        ItemRepository.getItem(context, ITEM_RING_OF_VIT).addEffect(new Item.Effect(GameChar.Attribute.VIT, 1));
        ItemRepository.getItem(context, ITEM_RING_OF_INT).addEffect(new Item.Effect(GameChar.Attribute.INT, 1));
        ItemRepository.getItem(context, ITEM_RING_OF_AGI).addEffect(new Item.Effect(GameChar.Attribute.AGI, 1));
        ItemRepository.getItem(context, ITEM_RING_OF_STR2).addEffect(new Item.Effect(GameChar.Attribute.STR, 2));
        ItemRepository.getItem(context, ITEM_RING_OF_VIT2).addEffect(new Item.Effect(GameChar.Attribute.VIT, 2));
        ItemRepository.getItem(context, ITEM_RING_OF_INT2).addEffect(new Item.Effect(GameChar.Attribute.INT, 2));
        ItemRepository.getItem(context, ITEM_RING_OF_AGI2).addEffect(new Item.Effect(GameChar.Attribute.AGI, 2));
        ItemRepository.getItem(context, ITEM_RING_OF_DEFENSE).addEffect(new Item.Effect(GameChar.Status.DEFENSE, 1));
        ItemRepository.getItem(context, ITEM_RING_OF_HITTING).addEffect(new Item.Effect(GameChar.Status.HIT_BONUS, 1));
        ItemRepository.getItem(context, ITEM_RING_OF_DODGE).addEffect(new Item.Effect(GameChar.Status.DODGE_BONUS, 1));
        ItemRepository.getItem(context, ITEM_RING_OF_CRITICAL).addEffect(new Item.Effect(GameChar.Status.CRITICAL, 2));
        ItemRepository.addShopItemToTown(context, 10, 1, 0);
        ItemRepository.addShopItemToTown(context, 10, 2, 0);
        ItemRepository.addShopItemToTown(context, 10, 3, 0);
        ItemRepository.addShopItemToTown(context, 10, 4, 0);
        ItemRepository.addShopItemToTown(context, 10, 5, 0);
        ItemRepository.addShopItemToTown(context, 10, 6, 0);
        ItemRepository.addShopItemToTown(context, 10, 7, 0);
        ItemRepository.addShopItemToTown(context, 10, 8, 0);
        ItemRepository.addShopItemToTown(context, 10, 9, 0);
        ItemRepository.addShopItemToTown(context, 10, 10, 0);
        ItemRepository.addShopItemToTown(context, 10, 11, 0);
        ItemRepository.addShopItemToTown(context, 10, 12, 0);
        ItemRepository.addShopItemToTown(context, 10, 13, 0);
        ItemRepository.addShopItemToTown(context, 20, 1, 0);
        ItemRepository.addShopItemToTown(context, 20, 2, 0);
        ItemRepository.addShopItemToTown(context, 20, 3, 0);
        ItemRepository.addShopItemToTown(context, 20, 4, 0);
        ItemRepository.addShopItemToTown(context, 20, 5, 0);
        ItemRepository.addShopItemToTown(context, 20, 6, 0);
        ItemRepository.addShopItemToTown(context, 20, 7, 0);
        ItemRepository.addShopItemToTown(context, 20, 8, 0);
        ItemRepository.addShopItemToTown(context, 20, 9, 0);
        ItemRepository.addShopItemToTown(context, 20, 10, 0);
        ItemRepository.addShopItemToTown(context, 20, 11, 0);
        ItemRepository.addShopItemToTown(context, 20, 12, 0);
        ItemRepository.addShopItemToTown(context, 20, 13, 0);
        ItemRepository.addShopItemToTown(context, 30, 4, 0);
        ItemRepository.addShopItemToTown(context, 30, 6, 0);
        ItemRepository.addShopItemToTown(context, 30, 7, 0);
        ItemRepository.addShopItemToTown(context, 30, 8, 0);
        ItemRepository.addShopItemToTown(context, 30, 9, 0);
        ItemRepository.addShopItemToTown(context, 30, 10, 0);
        ItemRepository.addShopItemToTown(context, 30, 12, 0);
        ItemRepository.addShopItemToTown(context, 30, 13, 0);
        ItemRepository.addShopItemToTown(context, 40, 4, 0);
        ItemRepository.addShopItemToTown(context, 40, 6, 0);
        ItemRepository.addShopItemToTown(context, 40, 7, 0);
        ItemRepository.addShopItemToTown(context, 40, 8, 0);
        ItemRepository.addShopItemToTown(context, 40, 9, 0);
        ItemRepository.addShopItemToTown(context, 40, 10, 0);
        ItemRepository.addShopItemToTown(context, 40, 12, 0);
        ItemRepository.addShopItemToTown(context, 40, 13, 0);
        ItemRepository.addShopItemToTown(context, 50, 7, 0);
        ItemRepository.addShopItemToTown(context, 50, 8, 0);
        ItemRepository.addShopItemToTown(context, 50, 9, 0);
        ItemRepository.addShopItemToTown(context, 60, 7, 0);
        ItemRepository.addShopItemToTown(context, 60, 8, 0);
        ItemRepository.addShopItemToTown(context, 60, 9, 0);
        ItemRepository.addShopItemToTown(context, 1020, 1, 0);
        ItemRepository.addShopItemToTown(context, 1020, 3, 0);
        ItemRepository.addShopItemToTown(context, 1030, 1, 0);
        ItemRepository.addShopItemToTown(context, 1030, 2, 0);
        ItemRepository.addShopItemToTown(context, 1030, 3, 0);
        ItemRepository.addShopItemToTown(context, 1030, 7, 0);
        ItemRepository.addShopItemToTown(context, 1030, 11, 0);
        ItemRepository.addShopItemToTown(context, 1030, 13, 0);
        ItemRepository.addShopItemToTown(context, 1040, 2, 0);
        ItemRepository.addShopItemToTown(context, 1040, 3, 0);
        ItemRepository.addShopItemToTown(context, 1040, 7, 0);
        ItemRepository.addShopItemToTown(context, 1050, 1, 0);
        ItemRepository.addShopItemToTown(context, 1050, 3, 0);
        ItemRepository.addShopItemToTown(context, 1050, 7, 0);
        ItemRepository.addShopItemToTown(context, 1050, 13, 0);
        ItemRepository.addShopItemToTown(context, 1060, 1, 0);
        ItemRepository.addShopItemToTown(context, 1060, 4, 0);
        ItemRepository.addShopItemToTown(context, 1060, 6, 0);
        ItemRepository.addShopItemToTown(context, 1060, 7, 0);
        ItemRepository.addShopItemToTown(context, 1060, 11, 0);
        ItemRepository.addShopItemToTown(context, 1060, 12, 0);
        ItemRepository.addShopItemToTown(context, 1060, 13, 0);
        ItemRepository.addShopItemToTown(context, 1070, 1, 0);
        ItemRepository.addShopItemToTown(context, 1070, 2, 0);
        ItemRepository.addShopItemToTown(context, 1070, 3, 0);
        ItemRepository.addShopItemToTown(context, 1070, 6, 0);
        ItemRepository.addShopItemToTown(context, 1070, 10, 0);
        ItemRepository.addShopItemToTown(context, 1070, 11, 0);
        ItemRepository.addShopItemToTown(context, 1080, 4, 0);
        ItemRepository.addShopItemToTown(context, 1080, 8, 0);
        ItemRepository.addShopItemToTown(context, 1090, 1, 0);
        ItemRepository.addShopItemToTown(context, 1090, 2, 0);
        ItemRepository.addShopItemToTown(context, 1090, 3, 0);
        ItemRepository.addShopItemToTown(context, 1090, 4, 0);
        ItemRepository.addShopItemToTown(context, 1090, 5, 0);
        ItemRepository.addShopItemToTown(context, 1090, 8, 0);
        ItemRepository.addShopItemToTown(context, 1090, 12, 0);
        ItemRepository.addShopItemToTown(context, 1110, 4, 0);
        ItemRepository.addShopItemToTown(context, 1110, 5, 0);
        ItemRepository.addShopItemToTown(context, 1110, 8, 0);
        ItemRepository.addShopItemToTown(context, 1110, 10, 0);
        ItemRepository.addShopItemToTown(context, 1110, 12, 0);
        ItemRepository.addShopItemToTown(context, 1120, 1, 0);
        ItemRepository.addShopItemToTown(context, 1120, 2, 0);
        ItemRepository.addShopItemToTown(context, 1120, 4, 0);
        ItemRepository.addShopItemToTown(context, 1120, 5, 0);
        ItemRepository.addShopItemToTown(context, 1120, 6, 0);
        ItemRepository.addShopItemToTown(context, 1120, 8, 0);
        ItemRepository.addShopItemToTown(context, 1120, 10, 0);
        ItemRepository.addShopItemToTown(context, 1120, 12, 0);
        ItemRepository.addShopItemToTown(context, 1140, 1, 0);
        ItemRepository.addShopItemToTown(context, 1140, 2, 0);
        ItemRepository.addShopItemToTown(context, 1140, 4, 0);
        ItemRepository.addShopItemToTown(context, 1140, 8, 0);
        ItemRepository.addShopItemToTown(context, 1140, 10, 0);
        ItemRepository.addShopItemToTown(context, 1140, 12, 0);
        ItemRepository.addShopItemToTown(context, 1150, 6, 0);
        ItemRepository.addShopItemToTown(context, 1160, 2, 0);
        ItemRepository.addShopItemToTown(context, 1160, 6, 0);
        ItemRepository.addShopItemToTown(context, 1170, 3, 0);
        ItemRepository.addShopItemToTown(context, 1170, 4, 0);
        ItemRepository.addShopItemToTown(context, 1170, 5, 0);
        ItemRepository.addShopItemToTown(context, 1170, 8, 0);
        ItemRepository.addShopItemToTown(context, 1170, 12, 0);
        ItemRepository.addShopItemToTown(context, 1180, 2, 0);
        ItemRepository.addShopItemToTown(context, 1180, 4, 0);
        ItemRepository.addShopItemToTown(context, 1180, 6, 0);
        ItemRepository.addShopItemToTown(context, 1180, 7, 0);
        ItemRepository.addShopItemToTown(context, 1180, 13, 0);
        ItemRepository.addShopItemToTown(context, 1190, 4, 0);
        ItemRepository.addShopItemToTown(context, 1190, 5, 0);
        ItemRepository.addShopItemToTown(context, 1190, 8, 0);
        ItemRepository.addShopItemToTown(context, 1190, 12, 0);
        ItemRepository.addShopItemToTown(context, 1200, 2, 0);
        ItemRepository.addShopItemToTown(context, 1200, 3, 0);
        ItemRepository.addShopItemToTown(context, 1200, 4, 0);
        ItemRepository.addShopItemToTown(context, 1200, 6, 0);
        ItemRepository.addShopItemToTown(context, 1200, 7, 0);
        ItemRepository.addShopItemToTown(context, 1200, 8, 0);
        ItemRepository.addShopItemToTown(context, 1200, 10, 0);
        ItemRepository.addShopItemToTown(context, 1200, 11, 0);
        ItemRepository.addShopItemToTown(context, 1200, 13, 0);
        ItemRepository.addShopItemToTown(context, 1210, 2, 0);
        ItemRepository.addShopItemToTown(context, 1210, 4, 0);
        ItemRepository.addShopItemToTown(context, 1210, 8, 0);
        ItemRepository.addShopItemToTown(context, 1210, 10, 0);
        ItemRepository.addShopItemToTown(context, 1210, 13, 0);
        ItemRepository.addShopItemToTown(context, 1220, 10, 0);
        ItemRepository.addShopItemToTown(context, 1220, 13, 0);
        ItemRepository.addShopItemToTown(context, 1230, 8, 0);
        ItemRepository.addShopItemToTown(context, 1230, 12, 0);
        ItemRepository.addShopItemToTown(context, 1240, 10, 0);
        ItemRepository.addShopItemToTown(context, 1250, 10, 0);
        ItemRepository.addShopItemToTown(context, 1260, 12, 0);
        ItemRepository.addShopItemToTown(context, 1270, 10, 0);
        ItemRepository.addShopItemToTown(context, 1130, 1, 0);
        ItemRepository.addShopItemToTown(context, 1130, 2, 0);
        ItemRepository.addShopItemToTown(context, 1130, 3, 0);
        ItemRepository.addShopItemToTown(context, 1130, 5, 0);
        ItemRepository.addShopItemToTown(context, 1130, 12, 0);
        ItemRepository.addShopItemToTown(context, 1550, 1, 0);
        ItemRepository.addShopItemToTown(context, 1550, 3, 0);
        ItemRepository.addShopItemToTown(context, 1550, 4, 0);
        ItemRepository.addShopItemToTown(context, 1550, 7, 0);
        ItemRepository.addShopItemToTown(context, 1560, 7, 0);
        ItemRepository.addShopItemToTown(context, 1560, 13, 0);
        ItemRepository.addShopItemToTown(context, ITEM_ROBE, 1, 0);
        ItemRepository.addShopItemToTown(context, ITEM_ROBE, 3, 0);
        ItemRepository.addShopItemToTown(context, ITEM_ROBE, 4, 0);
        ItemRepository.addShopItemToTown(context, ITEM_ROBE, 7, 0);
        ItemRepository.addShopItemToTown(context, ITEM_ROBE, 13, 0);
        ItemRepository.addShopItemToTown(context, ITEM_LEATHER_ARMOR, 1, 0);
        ItemRepository.addShopItemToTown(context, ITEM_LEATHER_ARMOR, 2, 0);
        ItemRepository.addShopItemToTown(context, ITEM_LEATHER_ARMOR, 3, 0);
        ItemRepository.addShopItemToTown(context, ITEM_LEATHER_ARMOR, 4, 0);
        ItemRepository.addShopItemToTown(context, ITEM_LEATHER_ARMOR, 5, 0);
        ItemRepository.addShopItemToTown(context, ITEM_LEATHER_ARMOR, 6, 0);
        ItemRepository.addShopItemToTown(context, ITEM_LEATHER_ARMOR, 7, 0);
        ItemRepository.addShopItemToTown(context, ITEM_LEATHER_ARMOR, 8, 0);
        ItemRepository.addShopItemToTown(context, ITEM_LEATHER_ARMOR, 10, 0);
        ItemRepository.addShopItemToTown(context, ITEM_LEATHER_ARMOR, 11, 0);
        ItemRepository.addShopItemToTown(context, ITEM_LEATHER_ARMOR, 13, 0);
        ItemRepository.addShopItemToTown(context, ITEM_RING_MAIL, 1, 0);
        ItemRepository.addShopItemToTown(context, ITEM_RING_MAIL, 2, 0);
        ItemRepository.addShopItemToTown(context, ITEM_RING_MAIL, 5, 0);
        ItemRepository.addShopItemToTown(context, ITEM_CHAIN_MAIL, 2, 0);
        ItemRepository.addShopItemToTown(context, ITEM_CHAIN_MAIL, 4, 0);
        ItemRepository.addShopItemToTown(context, ITEM_CHAIN_MAIL, 5, 0);
        ItemRepository.addShopItemToTown(context, ITEM_CHAIN_MAIL, 6, 0);
        ItemRepository.addShopItemToTown(context, ITEM_CHAIN_MAIL, 7, 0);
        ItemRepository.addShopItemToTown(context, ITEM_CHAIN_MAIL, 8, 0);
        ItemRepository.addShopItemToTown(context, ITEM_CHAIN_MAIL, 11, 0);
        ItemRepository.addShopItemToTown(context, ITEM_CHAIN_MAIL, 12, 0);
        ItemRepository.addShopItemToTown(context, ITEM_CHAIN_MAIL, 13, 0);
        ItemRepository.addShopItemToTown(context, ITEM_BREAST_PLATE, 3, 0);
        ItemRepository.addShopItemToTown(context, ITEM_BREAST_PLATE, 4, 0);
        ItemRepository.addShopItemToTown(context, ITEM_BREAST_PLATE, 12, 0);
        ItemRepository.addShopItemToTown(context, ITEM_PLATE_ARMOR, 4, 0);
        ItemRepository.addShopItemToTown(context, ITEM_PLATE_ARMOR, 5, 0);
        ItemRepository.addShopItemToTown(context, ITEM_PLATE_ARMOR, 8, 0);
        ItemRepository.addShopItemToTown(context, ITEM_PLATE_ARMOR, 12, 0);
        ItemRepository.addShopItemToTown(context, ITEM_LAMELLAR, 10, 0);
        ItemRepository.addShopItemToTown(context, ITEM_BUCKLER, 1, 0);
        ItemRepository.addShopItemToTown(context, ITEM_BUCKLER, 2, 0);
        ItemRepository.addShopItemToTown(context, ITEM_BUCKLER, 3, 0);
        ItemRepository.addShopItemToTown(context, ITEM_BUCKLER, 4, 0);
        ItemRepository.addShopItemToTown(context, ITEM_BUCKLER, 6, 0);
        ItemRepository.addShopItemToTown(context, ITEM_BUCKLER, 7, 0);
        ItemRepository.addShopItemToTown(context, ITEM_BUCKLER, 8, 0);
        ItemRepository.addShopItemToTown(context, ITEM_BUCKLER, 11, 0);
        ItemRepository.addShopItemToTown(context, ITEM_BUCKLER, 13, 0);
        ItemRepository.addShopItemToTown(context, ITEM_SMALL_SHIELD, 1, 0);
        ItemRepository.addShopItemToTown(context, ITEM_SMALL_SHIELD, 2, 0);
        ItemRepository.addShopItemToTown(context, ITEM_SMALL_SHIELD, 3, 0);
        ItemRepository.addShopItemToTown(context, ITEM_SMALL_SHIELD, 4, 0);
        ItemRepository.addShopItemToTown(context, ITEM_SMALL_SHIELD, 5, 0);
        ItemRepository.addShopItemToTown(context, ITEM_SMALL_SHIELD, 6, 0);
        ItemRepository.addShopItemToTown(context, ITEM_SMALL_SHIELD, 8, 0);
        ItemRepository.addShopItemToTown(context, ITEM_SMALL_SHIELD, 11, 0);
        ItemRepository.addShopItemToTown(context, ITEM_SMALL_SHIELD, 12, 0);
        ItemRepository.addShopItemToTown(context, ITEM_SMALL_SHIELD, 13, 0);
        ItemRepository.addShopItemToTown(context, ITEM_LARGE_SHIELD, 2, 0);
        ItemRepository.addShopItemToTown(context, ITEM_LARGE_SHIELD, 4, 0);
        ItemRepository.addShopItemToTown(context, ITEM_LARGE_SHIELD, 5, 0);
        ItemRepository.addShopItemToTown(context, ITEM_LARGE_SHIELD, 6, 0);
        ItemRepository.addShopItemToTown(context, ITEM_LARGE_SHIELD, 8, 0);
        ItemRepository.addShopItemToTown(context, ITEM_LARGE_SHIELD, 12, 0);
        ItemRepository.addShopItemToTown(context, ITEM_TOWER_SHIELD, 12, 0);
        ItemRepository.addShopItemToTown(context, ITEM_SYNTHETIC_CATALYST, 5, 0);
        ItemRepository.addShopItemToTown(context, ITEM_SYNTHETIC_CATALYST, 8, 0);
        ItemRepository.addShopItemToTown(context, ITEM_SYNTHETIC_CATALYST, 12, 0);
    }
}
