const $ = id => document.getElementById(id);
let state = createInitialGameState(12345), run = null, lastBattle = null, dialogueLines = ['“전투를 시작할 준비가 됐어.”','“모두 조심해서 가자.”'];

function makeParty(){return [new Character({id:'hero',name:'기사',hp:420,attack:62,defense:35,speed:12,team:'player'}),new Character({id:'mage',name:'마법사',hp:260,attack:88,defense:18,speed:16,team:'player'})];}
function battleFactory(rng,party,enemies){const events=[];const engine=new BattleEngine({rng,damageCalculator:new DamageCalculator(rng),onEvent:e=>events.push(e)});const started=performance.now();const result=engine.run(party,enemies);const seconds=Math.max(.1,(performance.now()-started)/1000);party.forEach(c=>c.stats.activeSeconds=(c.stats.activeSeconds||0)+seconds);return {party,enemies,events,result,seconds};}
function pick(a,rng){return a[rng.int(0,a.length-1)];}
function updateDialogue(events){if(!events?.length)return;const rng=run?.rng||new SeededRandom(Date.now());let key='attack';const e=events[events.length-1];if(e.type==='BATTLE_START')key='battle_start';else if(e.type==='DEFEAT')key=e.data.characterId==='hero'||e.data.characterId==='mage'?'ally_defeat':'enemy_defeat';else if(e.type==='MISS')key='miss';else if(e.type==='DAMAGE'&&e.data.critical)key='critical';else if(e.type==='BATTLE_END')key=e.result==='WIN'?'victory':'defeat';const pool=(window.DIALOGUES&&DIALOGUES[key])||DIALOGUES.attack;dialogueLines=[pick(pool,rng),pick(pool,rng)];}
function formatEvent(e){if(e.type==='DAMAGE')return `${e.data.attacker} → ${e.data.defender} ${e.data.damage} 피해${e.data.critical?' CRITICAL':''}`;if(e.type==='MISS')return `${e.data.attacker} → ${e.data.defender} 빗나감`;if(e.type==='DEFEAT')return `💥 ${e.data.character} 기절 (${e.data.defeatedBy}의 공격)`;return e.type;}
function dps(c){const seconds=Math.max(.1,c.stats.activeSeconds||0);return ((c.stats.damageDealt||0)/seconds).toFixed(1);}
function defeatedSummary(events){const names=(events||[]).filter(e=>e.type==='DEFEAT').map(e=>e.data.character);return names.length?` (${names.join(', ')} 기절)`:'';}
function render(){const d=run?.dungeon;$('dungeon').innerHTML=d?`<h3>${d.name}</h3><p>층 <b>${run.floor}</b> / ${d.floors}</p><p>${run.complete?'탐험 완료':run.active?'탐험 중':'탐험 종료'}</p><p>Seed: ${state.seed}</p>`:'<p>던전을 선택하고 탐험을 시작하세요.</p>';const party=run?.party||[];$('party').innerHTML=party.map(c=>`<div class="row"><b>${c.name}</b><span>HP ${Math.max(0,c.hp)}/${c.maxHp}</span><span>누적 DPS ${dps(c)}</span><span>피해 ${c.stats.damageDealt||0}</span></div>`).join('')||'<p>대기 중</p>';$('battle').innerHTML=lastBattle?`<p>결과: <b>${lastBattle.result.result}</b> / ${lastBattle.result.round} Round${defeatedSummary(lastBattle.events)}</p><p>전투시간 ${lastBattle.seconds.toFixed(2)}초 · 상세 로그 ${lastBattle.events.length}건</p>`:'<p>아직 전투가 없습니다.</p>';$('dialogue').innerHTML=dialogueLines.map(x=>`<div>${x}</div>`).join('');$('stats').innerHTML=run?`<p>골드 <b>${run.gold}</b> · 경험치 <b>${run.exp}</b></p>`+party.map(c=>`<div>${c.name}: ${c.stats.damageDealt||0} 피해 / ${c.stats.hits||0} 적중 / ${c.stats.criticals||0} 치명타 / ${c.stats.kills||0} 처치 / 누적 DPS ${dps(c)}</div>`).join(''):'<p>-</p>';$('loot').innerHTML=run?.loot.length?run.loot.map(x=>`<div class="loot"><span>${x.itemName} ×${x.quantity}</span><small>(층 ${x.floor})</small></div>`).join(''):'<p>획득 아이템 없음</p>';$('log').textContent=run?run.events.map((e,i)=>{if(e.type==='BATTLE')return `[${i+1}] ${e.floor}층 전투: ${e.result.result}${defeatedSummary(e.events)}\n`+e.events.map(x=>`  ${formatEvent(x)}`).join('\n');if(e.type==='LOOT')return `[${i+1}] ${e.floor}층 획득: ${e.itemName} ×${e.quantity}`;if(e.type==='FLOOR')return `[${i+1}] ${e.floor}층 진입`;if(e.type==='RUN_START')return `[${i+1}] 탐험 시작`;return `[${i+1}] 탐험 완료`;}).join('\n'):'탐험 로그가 없습니다.';$('status').textContent=run?.complete?'탐험 완료':run?.active?'탐험 진행 중 · 다음 진행 버튼으로 한 단계 진행':'준비';$('stepDungeon').disabled=!run||run.complete;}
function startDungeon(){const seed=Number($('seed').value)||12345;state=createInitialGameState(seed);state.seed=seed;const dungeon=DUNGEONS[$('dungeonSelect').value]||Object.values(DUNGEONS)[0];run=new DungeonRun({dungeon,party:makeParty(),rng:new SeededRandom(seed),battleFactory});run.start();run.nextFloor();lastBattle=null;dialogueLines=DIALOGUES.battle_start.slice();render();}
function stepDungeon(){if(!run){startDungeon();return}if(run.complete)return;const before=run.events.length;run.step();const added=run.events.slice(before);const battleEvents=added.filter(e=>e.type==='BATTLE');const last=battleEvents.at(-1);if(last){lastBattle={result:last.result,events:last.events,seconds:last.seconds||0};updateDialogue(last.events);}else updateDialogue(added);state.adventure={active:run.active,currentEvent:run.events.at(-1)?.type||null};render();}
function populateDungeons(){const select=$('dungeonSelect');Object.values(DUNGEONS).forEach(d=>{const option=document.createElement('option');option.value=d.id;option.textContent=`${d.name} (${d.floors}층)`;select.appendChild(option);});}
$('startDungeon').addEventListener('click',startDungeon);$('stepDungeon').addEventListener('click',stepDungeon);$('run100').addEventListener('click',()=>{const seed=Number($('seed').value)||12345;let wins=0;for(let i=0;i<100;i++){const b=battleFactory(new SeededRandom(seed+i),makeParty(),[new Character({id:'test-enemy',name:'훈련용 고블린',hp:220,attack:44,defense:18,speed:9,team:'enemy'})]);if(b.result.result==='WIN')wins++;}$('battle').innerHTML=`<p>100회 전투 완료</p><p>승리 <b>${wins}</b> / 100 · 승률 <b>${wins}%</b></p>`;});$('reset').addEventListener('click',()=>{run=null;lastBattle=null;dialogueLines=['“전투를 시작할 준비가 됐어.”','“모두 조심해서 가자.”'];state=createInitialGameState(12345);$('seed').value=12345;render();});try{populateDungeons();render();}catch(error){$('status').textContent='오류: '+error.message;$('log').textContent=error.stack||String(error);console.error(error);}
