const $ = id => document.getElementById(id);
let state = createInitialGameState(12345), run = null, lastBattle = null, partyPanel = null, dialogueLines = [];
function dialogueSet(key){return (window.DIALOGUES?.[key]||window.DIALOGUES?.default?.[key]||window.DIALOGUES?.default?.attack||['전투 준비!']);}
function makeParty(){const factory=new CharacterFactory();return (window.DUMMY_PARTY||[{id:'hero-dummy',name:'주인공(임시)',classId:'warrior'},{id:'mage-dummy',name:'세리아',classId:'mage'},{id:'rogue-dummy',name:'카인',classId:'rogue'}]).map(x=>factory.create({...x,team:'player'}));}
function battleFactory(rng,party,enemies){const engine=new BattleEngine({rng,damageCalculator:new DamageCalculator(rng)});const result=engine.run(party,enemies);return {party,enemies,events:result.events,result,seconds:Math.max(.1,(result.endedAt-result.startedAt)/1000)};}
function pick(a,rng){return a?.length?a[rng.int(0,a.length-1)]:'전투 준비!';}
function updateDialogue(events){if(!events?.length)return;const e=events[events.length-1];let key='attack';if(e.type==='BATTLE_START')key='battle_start';else if(e.type==='DEFEAT')key=e.data.side==='player'?'ally_defeat':'enemy_defeat';else if(e.type==='MISS')key='miss';else if(e.type==='DAMAGE'&&e.data.critical)key='critical';else if(e.type==='BATTLE_END')key=e.data.result==='WIN'?'victory':e.data.result==='LOSE'?'defeat':'attack';const rng=run?.rng||new SeededRandom(Date.now());const pool=dialogueSet(key);dialogueLines=[pick(pool,rng),pick(pool,rng)];}
function formatEvent(e){if(e.type==='DAMAGE')return `${e.data.attacker} → ${e.data.defender} ${e.data.damage} 피해${e.data.critical?' CRITICAL':''}`;if(e.type==='MISS')return `${e.data.attacker} → ${e.data.defender} 빗나감`;if(e.type==='DEFEAT')return `💥 ${e.data.character} 기절 (${e.data.defeatedBy}의 공격)`;return e.type;}
function defeatedSummary(events){const names=(events||[]).filter(e=>e.type==='DEFEAT').map(e=>e.data.character);return names.length?` (${names.join(', ')} 기절)`:'';}
function dps(c){const s=run?.stats?.[c.id];return s?.activeSeconds?Number((s.damage/s.activeSeconds).toFixed(1)):0;}
function render(){const d=run?.dungeon;$('dungeon').innerHTML=d?`<h3>${d.name}</h3><p>층 <b>${Math.min(run.floor,d.floors)}</b> / ${d.floors}</p><p>${run.complete?'탐험 완료':run.active?'탐험 중':'탐험 종료'}</p><p>Seed: ${state.seed}</p><p>Gold ${run.gold} · EXP ${run.exp}</p>`:'<p>던전을 선택하고 탐험을 시작하세요.</p>';const party=run?.party||[];if(!partyPanel)partyPanel=new PartyPanel({container:$('party'),party,run});else{partyPanel.party=party;partyPanel.run=run;}partyPanel.render();$('battle').innerHTML=lastBattle?`<p>결과: <b>${lastBattle.result.result}</b> / ${lastBattle.result.round} Round${defeatedSummary(lastBattle.events)}</p><p>전투시간 ${lastBattle.seconds.toFixed(2)}초 · 상세 로그 ${lastBattle.events.length}건</p>`:'<p>아직 전투가 없습니다.</p>';$('dialogue').innerHTML=(dialogueLines.length?dialogueLines:dialogueSet('battle_start')).map(x=>`<div>${x}</div>`).join('');$('stats').innerHTML=run?party.map(c=>{const s=run.stats[c.id]||{};return `<div>${c.name}: ${s.damage||0} 피해 / ${s.hits||0} 적중 / ${s.criticals||0} 치명타 / ${s.kills||0} 처치 / 누적 DPS ${dps(c)}</div>`}).join(''):'<p>-</p>';$('loot').innerHTML=run?.loot.length?run.loot.map(x=>`<div class="loot"><span>${x.itemName} ×${x.quantity}</span><small>(층 ${x.floor})</small></div>`).join(''):'<p>획득 아이템 없음</p>';$('log').textContent=run?run.events.map((e,i)=>{if(e.type==='BATTLE_END')return `[${i+1}] ${e.floor}층 전투: ${e.data.result}${defeatedSummary(e.data.events)}\n`+e.data.events.map(formatEvent).join('\n');if(e.type==='LOOT')return `[${i+1}] ${e.floor}층 획득: ${e.data.itemName} ×${e.data.quantity}`;if(e.type==='FLOOR_REACHED')return `[${i+1}] ${e.floor}층 진입`;if(e.type==='RUN_START')return `[${i+1}] 탐험 시작`;return `[${i+1}] ${e.type}`}).join('\n'):'탐험 로그가 없습니다.';$('status').textContent=run?.complete?'탐험 완료':run?.active?'탐험 진행 중 · 다음 진행 버튼으로 한 단계 진행':'준비';$('stepDungeon').disabled=!run||run.complete;}
function startDungeon(){try{const seed=Number($('seed').value)||12345;state=createInitialGameState(seed);state.seed=seed;const dungeon=DUNGEONS[$('dungeonSelect').value]||Object.values(DUNGEONS)[0];if(!dungeon)throw new Error('등록된 던전이 없습니다.');run=new DungeonRun({dungeon,party:makeParty(),rng:new SeededRandom(seed),battleFactory});run.start();run.nextFloor();lastBattle=null;dialogueLines=dialogueSet('battle_start').slice();if(window.initQuestUI)initQuestUI();renderQuests?.();render();}catch(error){$('status').textContent='탐험 시작 오류: '+error.message;$('log').textContent=error.stack||String(error);console.error(error);}}
function stepDungeon(){try{if(!run){startDungeon();return}if(run.complete)return;const before=run.events.length;run.step();const added=run.events.slice(before);const battle=added.find(e=>e.type==='BATTLE_END');if(battle){lastBattle={result:{result:battle.data.result,round:battle.data.round},events:battle.data.events,seconds:Math.max(.1,battle.data.events.length/10)};updateDialogue(battle.data.events);}else updateDialogue(added);state.adventure={active:run.active,currentEvent:run.events.at(-1)?.type||null};render();}catch(error){$('status').textContent='진행 오류: '+error.message;$('log').textContent=error.stack||String(error);console.error(error);}}
function populateDungeons(){const select=$('dungeonSelect');select.innerHTML='';Object.values(DUNGEONS).forEach(d=>{const option=document.createElement('option');option.value=d.id;option.textContent=`${d.name} (${d.floors}층)`;select.appendChild(option);});}
$('startDungeon').addEventListener('click',startDungeon);$('stepDungeon').addEventListener('click',stepDungeon);$('run100').addEventListener('click',()=>{try{let wins=0;for(let i=0;i<100;i++){const b=battleFactory(new SeededRandom(Number($('seed').value||12345)+i),makeParty(),[new Character({id:'test-enemy',name:'훈련용 고블린',hp:220,attack:44,defense:18,speed:9,team:'enemy'})]);if(b.result.result==='WIN')wins++;}$('battle').innerHTML=`<p>100회 전투 완료</p><p>승리 <b>${wins}</b> / 100 · 승률 <b>${wins}%</b></p>`;}catch(error){$('status').textContent='100회 테스트 오류: '+error.message;}});$('reset').addEventListener('click',()=>{run=null;lastBattle=null;partyPanel=null;dialogueLines=dialogueSet('battle_start').slice();state=createInitialGameState(12345);$('seed').value=12345;if(window.initQuestUI)initQuestUI();renderQuests?.();render();});try{populateDungeons();dialogueLines=dialogueSet('battle_start').slice();render();}catch(error){$('status').textContent='초기화 오류: '+error.message;$('log').textContent=error.stack||String(error);console.error(error);}
