(() => {
  function leveledCharacter(level,classId){const f=new CharacterFactory();const base=window.CHARACTER_CLASSES?.[classId]||{};const c=f.create({id:`balance-${classId}-${level}`,name:classId,team:'player',classId,hp:base.hp,maxHp:base.hp,attack:base.attack,defense:base.defense,speed:base.speed,attributes:{...(base.attributes||{})}});const target=Math.max(1,Math.min(50,Number(level)||1));for(let n=1;n<target;n++)window.CharacterProgression?.applyLevel?.(c);c.level=target;c.hp=c.maxHp;return c;}
  function equipBest(c,level){const loader=window.EquipmentXmlLoader;if(!loader?.state?.loaded)return c;for(const slot of ['weapon','armor','accessory']){const pool=loader.pool(level,{slot}).filter(i=>c.canEquip(i).ok);if(!pool.length)continue;pool.sort((a,b)=>(Number(b.attack)||0)-(Number(a.attack)||0));c.equip(pool[0]);}return c;}
  function attackRange(level,classId,defenderDefense=0){const c=equipBest(leveledCharacter(level,classId),level);const atk=Number(c.attack)||0;const d=Number(defenderDefense)||0;return{minDamage:Math.max(1,atk+2-d),maxDamage:Math.max(1,atk+12-d),attack:atk,defense:c.defense};}
  function partyReference(level,defense=0){const classes=['warrior','mage','rogue'];const characters=classes.map(classId=>{const r=attackRange(level,classId,defense);return{id:classId,classId,...r,referenceDamage:(r.maxDamage+r.minDamage)/1.5};});const avgMin=characters.reduce((s,c)=>s+c.minDamage,0)/3;const avgMax=characters.reduce((s,c)=>s+c.maxDamage,0)/3;return{level,defense,characters,partyDamage:(avgMax+avgMin)/1.5*2};}
  function dungeonBoss(dungeon){const areas=Array.isArray(dungeon?.areas)?dungeon.areas:[];const last=Math.max(...areas.map(a=>Number(a.area)||0),Number(dungeon?.areaCount)||Number(dungeon?.floors)||0);const e=areas.find(a=>Number(a.area)===last)?.encounters||[];const names=e.flatMap(x=>x.enemies||x.monsters||[]).map(x=>typeof x==='string'?x:x.name).filter(Boolean);return names.map(name=>window.MonsterXmlLoader?.state?.items?.find(m=>m.dungeonName===(dungeon.monsterDungeonName||dungeon.name)&&m.name===name)).filter(Boolean).find(m=>String(m.grade).toLowerCase()==='boss'||String(m.form).toLowerCase()==='boss')||null;}
  function levelForDungeon(dungeon){return Math.max(1,Math.min(50,Number(dungeon?.levelEnd||dungeon?.levelStart||dungeon?.levelMap?.slice(-1)[0]||1)));}
  function makeParty(level){return ['warrior','mage','rogue'].map(classId=>equipBest(leveledCharacter(level,classId),level));}
  function simulateBoss(dungeon,bossHp,runs=1000,seed=12345){const boss=dungeonBoss(dungeon);if(!boss)return null;const results={wins:0,losses:0,draws:0,rounds:0};for(let i=0;i<runs;i++){const rng=new SeededRandom(Number(seed)+i*1009);const party=makeParty(levelForDungeon(dungeon));const enemy=new Character({id:`balance-boss-${i}`,name:boss.name,hp:bossHp,maxHp:bossHp,attack:Number(boss.attack)||0,defense:Number(boss.defense)||0,speed:10,team:'enemy',level:Number(boss.level)||levelForDungeon(dungeon),monsterId:boss.id,monsterGrade:boss.grade,monsterForm:boss.form});const engine=new BattleEngine({rng,damageCalculator:new DamageCalculator(rng)});const result=engine.run(party,[enemy]);if(result.result==='WIN')results.wins++;else if(result.result==='LOSE')results.losses++;else results.draws++;results.rounds+=Number(result.round)||0;}return{runs,wins:results.wins,losses:results.losses,draws:results.draws,winRate:results.wins/runs,avgRounds:results.rounds/runs};}
  function findBossHp90(dungeon,{runs=1000,seed=12345,maxHp=null}={}){const boss=dungeonBoss(dungeon);if(!boss)return null;const upper=Math.max(1,Number(maxHp)||Number(boss.maxHp)||1);const ref=partyReference(levelForDungeon(dungeon),boss.defense);let lo=1,hi=upper,best=1,bestSim=null;while(lo<=hi){const mid=Math.floor((lo+hi)/2);const sim=simulateBoss(dungeon,mid,runs,seed);if(sim&&sim.winRate>=0.9){best=mid;bestSim=sim;lo=mid+1;}else hi=mid-1;}return{dungeon:dungeon.name,level:levelForDungeon(dungeon),boss:{id:boss.id,name:boss.name,oldHp:Number(boss.maxHp)||0,attack:Number(boss.attack)||0,defense:Number(boss.defense)||0},reference:ref,recommendedHp:best,simulation:bestSim};}
  function report(dungeon){const boss=dungeonBoss(dungeon);if(!boss)return null;const level=levelForDungeon(dungeon);return{dungeon:dungeon.name,level,boss:{id:boss.id,name:boss.name,hp:boss.maxHp,attack:boss.attack,defense:boss.defense},reference:partyReference(level,boss.defense)};}
  window.BattleBalanceCalculator={leveledCharacter,equipBest,attackRange,partyReference,dungeonBoss,levelForDungeon,makeParty,simulateBoss,findBossHp90,report};
})();
