(() => {
  const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
  function levelCharacter(level,classId){const f=new CharacterFactory();const base=window.CHARACTER_CLASSES?.[classId]||{};return f.create({id:`balance-${classId}-${level}`,name:classId,team:'player',classId,level,hp:base.hp,maxHp:base.hp,attack:base.attack,defense:base.defense,speed:base.speed,attributes:{...(base.attributes||{})}});}
  function equipBest(c,level,mode){const loader=window.EquipmentXmlLoader;if(!loader?.state?.loaded)return c;for(const slot of ['weapon','armor','accessory']){const pool=loader.pool(level,{slot}).filter(i=>c.canEquip(i).ok);if(!pool.length)continue;pool.sort((a,b)=>{const av=mode==='max'?(Number(a.attack)||0):(Number(a.attack)||0);const bv=mode==='max'?(Number(b.attack)||0):(Number(b.attack)||0);return bv-av;});c.equip(pool[0]);}return c;}
  function attackRange(level,classId,defenderDefense=0){const out={};for(const mode of ['min','max']){const c=equipBest(levelCharacter(level,classId),level,mode);const atk=Number(c.attack)||0;const d=Number(defenderDefense)||0;out[mode]=Math.max(1,atk+(mode==='min'?2:12)-d);}return {...out,attack:levelCharacter(level,classId).attack};}
  function partyReference(level,defense=0){const classes=['warrior','mage','rogue'];const chars=classes.map(id=>{const c=equipBest(levelCharacter(level,id),level,'max');const min=Math.max(1,c.attack+2-defense);const max=Math.max(1,c.attack+12-defense);return{id,classId:id,minDamage:min,maxDamage:max,referenceDamage:(max+min)/1.5,attack:c.attack};});const maxSum=chars.reduce((s,c)=>s+c.maxDamage,0);const minSum=chars.reduce((s,c)=>s+c.minDamage,0);return{level,defense,characters:chars,partyDamage:((maxSum/3)+(minSum/3))/1.5*2};}
  function dungeonBoss(dungeon){const areas=dungeon?.areas||[];const last=Math.max(...areas.map(a=>Number(a.area)||0),Number(dungeon?.areaCount)||Number(dungeon?.floors)||0);const e=areas.find(a=>Number(a.area)===last)?.encounters||[];const names=e.flatMap(x=>x.enemies||x.monsters||[]);return names.map(x=>typeof x==='string'?x:x.name).map(name=>window.MonsterXmlLoader?.state?.items?.find(m=>m.dungeonName===(dungeon.monsterDungeonName||dungeon.name)&&m.name===name)).filter(Boolean).find(m=>String(m.grade).toLowerCase()==='boss'||String(m.form).toLowerCase()==='boss')||null;}
  function levelForDungeon(dungeon){return Number(dungeon?.levelEnd||dungeon?.levelStart||dungeon?.levelMap?.slice(-1)[0]||1);}
  function report(dungeon){const boss=dungeonBoss(dungeon);if(!boss)return null;const level=levelForDungeon(dungeon);const reference=partyReference(level,boss.defense);return{dungeon:dungeon.name,level,boss:{id:boss.id,name:boss.name,hp:boss.maxHp,attack:boss.attack,defense:boss.defense},reference};}
  window.BattleBalanceCalculator={levelCharacter,equipBest,attackRange,partyReference,dungeonBoss,report};
})();
