class DungeonRun {
  constructor({ dungeon, party, rng, battleFactory, onEvent=()=>{} }) {
    this.runId=`run-${Date.now()}`;this.dungeon=dungeon;this.party=Array.isArray(party)?party:[];this.rng=rng;this.battleFactory=battleFactory;this.onEvent=onEvent;this.floor=0;this.encounterIndex=0;this.active=false;this.complete=false;this.failed=false;this.bossReady=false;this.gold=0;this.exp=0;this.loot=[];this.events=[];this.startedAt=null;this.currentBattle=null;this.stats={};
    this.party.forEach(c=>this.stats[c.id]={damage:0,damageTaken:0,hits:0,attacks:0,criticals:0,kills:0,activeSeconds:0});
  }
  emit(type,data={}){const e={type,floor:this.floor,data};this.events.push(e);this.onEvent(e);}
  areaCount(){const d=this.dungeon||{};const declared=Number(d.areaCount);if(Number.isFinite(declared)&&declared>0)return Math.floor(declared);const areas=Array.isArray(d.areas)?d.areas:[];const maxArea=areas.reduce((max,a)=>Math.max(max,Number(a?.area)||0),0);if(maxArea>0)return maxArea;const count=Number(d.floors);return Number.isFinite(count)&&count>0?Math.floor(count):0;}
  start(){this.active=true;this.complete=false;this.failed=false;this.bossReady=false;this.floor=0;this.encounterIndex=0;this.startedAt=Date.now();this.loot=[];if(!Array.isArray(window.GAME_INVENTORY))window.GAME_INVENTORY=Array.isArray(window.playerInventory)?window.playerInventory:[];if(window.playerState?.inventory!==window.GAME_INVENTORY)window.playerState=window.playerState||{},window.playerState.inventory=window.GAME_INVENTORY;this.emit('RUN_START',{floor:1,areaCount:this.areaCount(),maxEncountersPerArea:5});return this;}
  addBattleStats(wrapper){const battle=wrapper?.result||wrapper;const players=Array.isArray(battle?.players)?battle.players:this.party;for(const c of players){if(!c)continue;const s=this.stats[c.id]||(this.stats[c.id]={damage:0,damageTaken:0,hits:0,attacks:0,criticals:0,kills:0,activeSeconds:0});const cs=c.stats||{};s.damage+=Number(cs.damageDealt)||0;s.damageTaken+=Number(cs.damageTaken)||0;s.hits+=Number(cs.hits)||0;s.attacks+=Number(cs.attacks)||0;s.criticals+=Number(cs.criticals)||0;s.kills+=Number(cs.kills)||0;s.activeSeconds+=Math.max(.1,Number(wrapper?.seconds)||.1);}}
  monsterExp(enemies){return (Array.isArray(enemies)?enemies:[]).reduce((sum,e)=>sum+Number(e?.exp||e?.experience||0),0);}
  distributePartyExp(amount){const members=this.party.filter(Boolean);if(!members.length||amount<=0)return[];const count=members.length;const total=Math.max(0,Math.floor(Number(amount)||0));const base=Math.floor(total/count);let remainder=total-(base*count);return members.map(c=>{const share=base+(remainder>0?1:0);if(remainder>0)remainder--;return{character:c,amount:share};});}
  awardBattleExp(result,enemies=[]){if(result!=='WIN')return 0;const amount=this.monsterExp(enemies);if(amount<=0)return 0;this.exp+=amount;const distribution=this.distributePartyExp(amount);for(const {character:c,amount:gainedExp} of distribution){if(typeof c.gainExp!=='function')continue;const gained=c.gainExp(gainedExp);if(gained.levels>0)this.emit('LEVEL_UP',{characterId:c.id,character:c.name,levels:gained.levels,level:c.level,exp:c.exp,expToNext:c.expToNextLevel()});}this.emit('EXP_GAIN',{amount,partySize:distribution.length,distribution:distribution.map(({character:c,amount:gainedExp})=>({characterId:c.id,name:c.name,amount:gainedExp,level:c.level,exp:c.exp}))});return amount;}
  getXmlEnemies(){if(!window.MonsterXmlLoader?.state?.loaded)return null;const resolver=window.EncounterResolver;if(resolver?.areaHasSpecial?.(this.dungeon,this.floor)&&this.encounterIndex===0&&resolver.resolveSpecial){const special=resolver.resolveSpecial(this.dungeon,this.floor);if(special.length)return special;}if(resolver?.resolve)return resolver.resolve(this.dungeon,this.floor,this.rng);const name=this.dungeon?.monsterDungeonName||this.dungeon?.name;const target=Math.max(1,Math.min(50,Number(this.dungeon?.levelMap?.[Math.max(0,this.floor-1)])||Number(this.floor)||1));const pool=window.MonsterXmlLoader.getForDungeon(name,target)||window.MonsterXmlLoader.getForDungeon(name)||[];return pool.length?[this.rng.pick(pool)]:null;}
  createXmlEncounter(){const pool=this.getXmlEnemies();if(!pool?.length)return null;return pool.map((m,index)=>{const balance=window.BattleBalanceCalculator?.calculateMonsterStats?.(m)||m;return new Character({id:`monster-${m.id}-${this.floor}-${this.encounterIndex}-${index}`,name:m.name,hp:balance.hp,maxHp:balance.maxHp,attack:balance.attack,defense:balance.defense,speed:10,team:'enemy',exp:m.exp,level:m.level,monsterLevel:m.level,monsterId:m.id,monsterGrade:m.grade,monsterForm:m.form,placement:m.placement,balanceSource:balance});});}
  fight(enemies){const wrapper=this.battleFactory(this.rng,this.party,enemies);const battle=wrapper?.result||wrapper;this.currentBattle=wrapper;this.addBattleStats(wrapper);const result=battle?.result||'DRAW';const events=Array.isArray(battle?.events)?battle.events:[];const enemyData=(Array.isArray(enemies)?enemies:[]).map(e=>({id:e.monsterId||e.id,name:e.name,grade:e.monsterGrade||e.grade,level:e.monsterLevel||e.level||null,form:e.monsterForm||e.form||null,placement:e.placement||null,hp:e.maxHp,attack:e.attack,defense:e.defense}));this.emit('BATTLE_END',{result,round:Number(battle?.round)||0,encounter:this.encounterIndex+1,area:this.floor,enemies:enemyData,events});this.awardBattleExp(result,enemies);if(result==='WIN')this.addEquipmentLoot({level:this.currentAreaLevel(enemies)});return wrapper;}
  currentAreaLevel(enemies=[]){const levels=(enemies||[]).map(e=>Number(e?.monsterLevel||e?.level)).filter(Number.isFinite);return Math.min(50,Math.max(1,levels.length?Math.max(...levels):Number(this.floor)||1));}
  addEquipmentLoot({boss=false,baseId=null,pool=null,force=false,level=null}={}){if(!window.LootSystem?.generate)return null;const item=window.LootSystem.generate({rng:this.rng,baseId,pool,force,boss,level:Math.min(50,Math.max(1,Number(level)||this.currentAreaLevel()))});if(!item)return null;if(!Array.isArray(window.GAME_INVENTORY))window.GAME_INVENTORY=[];if(!window.GAME_INVENTORY.some(x=>x?.instanceId===item.instanceId))window.GAME_INVENTORY.push(item);if(typeof window.addLootInstance==='function')window.addLootInstance(item);window.playerInventory=window.GAME_INVENTORY;if(window.playerState)window.playerState.inventory=window.GAME_INVENTORY;this.loot.push({itemId:item.baseId,itemName:item.name,quantity:1,floor:this.floor,instanceId:item.instanceId,rarity:item.rarity,rarityName:item.rarityName,enhancement:item.enhancement,options:item.options,equipment:item});this.emit('LOOT',{itemId:item.baseId,itemName:item.name,quantity:1,floor:this.floor,instanceId:item.instanceId,rarity:item.rarity,rarityName:item.rarityName,enhancement:item.enhancement,options:item.options,equipment:item});return item;}
  addLoot(itemId,itemName,quantity,gold=0){const item={itemId,itemName,quantity,floor:this.floor};this.loot.push(item);this.gold+=gold;this.emit('LOOT',{...item,gold});}
  isBossArea(area=this.floor){return Boolean(window.EncounterResolver?.areaHasBoss?.(this.dungeon,area)||window.EncounterResolver?.areaHasSpecial?.(this.dungeon,area));}
  nextFloor(){if(!this.active)return{done:true};this.floor++;this.encounterIndex=0;const totalAreas=this.areaCount();if(this.floor>totalAreas){this.complete=true;this.active=false;this.emit('RUN_COMPLETE',{floor:this.floor-1,areaCount:totalAreas});return{done:true};}if(this.isBossArea(this.floor)){this.floor--;this.encounterIndex=this.getAreaMaxEncounters(this.floor);this.bossReady=true;this.emit('BOSS_READY',{area:this.floor+1,bossArea:this.floor+1,previousArea:this.floor});return{done:false,bossReady:true,area:this.floor};}this.emit('FLOOR_REACHED',{floor:this.floor,area:this.floor,areaCount:totalAreas,maxEncounters:this.getAreaMaxEncounters(this.floor)});return{done:false,floor:this.floor};}
  getAreaMaxEncounters(area=this.floor){return this.isBossArea(area)?1:5;}
  restorePartyForBoss(){for(const c of this.party){if(!c)continue;c.hp=Math.max(0,Number(c.maxHp)||0);c.mp=Math.max(0,Number(c.maxMp)||0);}}
  fightBoss(){if(!this.active||!this.bossReady)return{done:false,bossReady:false};const bossArea=this.floor+1;if(bossArea>this.areaCount()){this.complete=true;this.active=false;this.bossReady=false;this.emit('RUN_COMPLETE',{floor:this.floor,areaCount:this.areaCount()});return{done:true};}this.restorePartyForBoss();this.floor=bossArea;this.encounterIndex=0;this.bossReady=false;this.emit('FLOOR_REACHED',{floor:this.floor,area:this.floor,areaCount:this.areaCount(),maxEncounters:1,bossBattle:true});const enemies=this.getXmlEnemies();if(!enemies?.length){this.active=false;this.failed=true;this.emit('RUN_FAILED',{floor:this.floor,area:this.floor,encounter:1,round:0,result:'NO_BOSS',enemies:[],battleEvents:[]});return{done:true,failed:true};}const battle=this.fight(enemies);const result=battle?.result?.result||battle?.result||'DRAW';const battleResult=battle?.result||{};const battleEvents=Array.isArray(battleResult.events)?battleResult.events:[];const battleEnemies=(Array.isArray(enemies)?enemies:[]).map(e=>({id:e.monsterId||e.id,name:e.name,level:e.monsterLevel||e.level||null,grade:e.monsterGrade||e.grade||null,form:e.monsterForm||e.form||null,placement:e.placement||null,hp:e.maxHp,attack:e.attack,defense:e.defense}));if(result!=='WIN'){this.active=false;this.complete=false;this.failed=true;this.emit('RUN_FAILED',{floor:this.floor,area:this.floor,encounter:1,round:Number(battle?.round)||0,result,enemies:battleEnemies,battleEvents});return{done:true,battle:this.currentBattle,failed:true,bossBattle:true};}this.encounterIndex=1;this.emit('AREA_ENCOUNTER',{area:this.floor,encounter:1,maxEncounters:1,remaining:0});this.addEquipmentLoot({boss:true,level:this.currentAreaLevel(enemies)});this.addLoot('boss-cache','수호자의 보물',1,500);if(this.floor===this.areaCount()){this.complete=true;this.active=false;this.emit('RUN_COMPLETE',{floor:this.floor,areaCount:this.areaCount()});}return{done:this.complete,battle:this.currentBattle,bossBattle:true,area:this.floor,encounter:1,maxEncounters:1};}
  step(){
    if(!this.active)return{done:true,battle:null};
    const totalAreas=this.areaCount();
    if(totalAreas<=0){this.complete=true;this.active=false;this.emit('RUN_COMPLETE',{floor:this.floor,areaCount:0});return{done:true,battle:null};}
    if(this.floor===0)this.nextFloor();
    const maxEncounters=this.getAreaMaxEncounters(this.floor);
    if(this.encounterIndex>=maxEncounters){
      if(this.floor===totalAreas){this.complete=true;this.active=false;this.emit('RUN_COMPLETE',{floor:this.floor,areaCount:totalAreas});return{done:true,battle:null};}
      const nextArea=this.floor+1;
      if(this.isBossArea(nextArea)){this.bossReady=true;this.encounterIndex=0;this.emit('BOSS_READY',{area:nextArea,bossArea:nextArea,previousArea:this.floor});}
      else this.nextFloor();
    }
    let enemies=this.createXmlEncounter();
    if(!enemies?.length){const area=Array.isArray(this.dungeon.areas)?this.dungeon.areas.find(x=>Number(x.area)===Number(this.floor)):null;const encounters=Array.isArray(area?.encounters)?area.encounters:[];const encounter=encounters.length?encounters[this.rng.int(0,encounters.length-1)]:null;if(encounter?.type==='treasure'){if(encounter.itemId&&window.EQUIPMENT?.[encounter.itemId])this.addEquipmentLoot({baseId:encounter.itemId,force:true});else this.addLoot(encounter.itemId,encounter.itemName,encounter.quantity,encounter.gold);}else if(encounter?.type==='battle'&&Array.isArray(encounter.enemies))enemies=encounter.enemies.map(e=>new Character({...e,team:'enemy'}));}
    if(enemies?.length){const isBoss=window.EncounterResolver?.isBoss?window.EncounterResolver.isBoss(enemies):Boolean(enemies.some(e=>e.placement==='boss'||e.monsterGrade==='boss'||e.monsterForm==='boss'));const battle=this.fight(enemies);const result=battle?.result?.result||battle?.result||'DRAW';if(result!=='WIN'){this.active=false;this.complete=false;this.failed=true;this.emit('RUN_FAILED',{floor:this.floor,area:this.floor,encounter:this.encounterIndex+1,round:Number(battle?.round)||0,result,enemies:enemies.map(e=>({id:e.monsterId||e.id,name:e.name,level:e.monsterLevel||e.level||null,grade:e.monsterGrade||e.grade||null,form:e.monsterForm||e.form||null,placement:e.placement||null})),battleEvents:Array.isArray(battle?.result?.events)?battle.result.events:[]});return{done:true,battle:this.currentBattle,failed:true,area:this.floor,encounter:this.encounterIndex+1,maxEncounters};}if(isBoss){this.addEquipmentLoot({boss:true,level:this.currentAreaLevel(enemies)});this.addLoot('boss-cache','수호자의 보물',1,500);}}
    this.encounterIndex++;
    this.emit('AREA_ENCOUNTER',{area:this.floor,encounter:this.encounterIndex,maxEncounters:this.bossReady?0:maxEncounters,remaining:Math.max(0,maxEncounters-this.encounterIndex)});
    if(this.active&&!this.bossReady&&this.encounterIndex>=maxEncounters){
      if(this.floor===totalAreas){this.complete=true;this.active=false;this.emit('RUN_COMPLETE',{floor:this.floor,areaCount:totalAreas});}
      else if(this.isBossArea(this.floor+1)){this.bossReady=true;this.encounterIndex=0;this.emit('BOSS_READY',{area:this.floor+1,bossArea:this.floor+1,previousArea:this.floor});}
      else this.nextFloor();
    } else if(this.active&&this.bossReady&&this.encounterIndex>=maxEncounters){this.encounterIndex=0;}
    return{done:this.complete,battle:this.currentBattle,area:this.floor,encounter:this.encounterIndex,maxEncounters,bossReady:this.bossReady};
  }
  getDps(id){const s=this.stats[id];return s&&s.activeSeconds?Math.round(s.damage/s.activeSeconds):0;}
  summary(){return{runId:this.runId,dungeonId:this.dungeon.id,floor:this.floor,areaCount:this.areaCount(),complete:this.complete,failed:this.failed,bossReady:this.bossReady,gold:this.gold,exp:this.exp,loot:this.loot,inventory:Array.isArray(window.GAME_INVENTORY)?window.GAME_INVENTORY:[],stats:this.stats,dps:Object.fromEntries(this.party.map(c=>[c.id,this.getDps(c.id)])),events:this.events};}
}
window.DungeonRun=DungeonRun;
