class DungeonRun {
  constructor({ dungeon, party, rng, battleFactory, onEvent=()=>{} }) {
    this.runId=`run-${Date.now()}`;this.dungeon=dungeon;this.party=Array.isArray(party)?party:[];this.rng=rng;this.battleFactory=battleFactory;this.onEvent=onEvent;this.floor=0;this.encounterIndex=0;this.active=false;this.complete=false;this.gold=0;this.exp=0;this.loot=[];this.events=[];this.startedAt=null;this.currentBattle=null;this.stats={};
    this.party.forEach(c=>this.stats[c.id]={damage:0,damageTaken:0,hits:0,attacks:0,criticals:0,kills:0,activeSeconds:0});
  }
  emit(type,data={}){const e={type,floor:this.floor,data};this.events.push(e);this.onEvent(e);}
  start(){this.active=true;this.complete=false;this.floor=0;this.startedAt=Date.now();this.loot=[];if(!Array.isArray(window.GAME_INVENTORY))window.GAME_INVENTORY=Array.isArray(window.playerInventory)?window.playerInventory:[];if(window.playerState?.inventory!==window.GAME_INVENTORY)window.playerState=window.playerState||{},window.playerState.inventory=window.GAME_INVENTORY;this.emit('RUN_START',{floor:1});return this;}
  addBattleStats(wrapper){const battle=wrapper?.result||wrapper;const players=Array.isArray(battle?.players)?battle.players:this.party;for(const c of players){if(!c)continue;const s=this.stats[c.id]||(this.stats[c.id]={damage:0,damageTaken:0,hits:0,attacks:0,criticals:0,kills:0,activeSeconds:0});const cs=c.stats||{};s.damage+=Number(cs.damageDealt)||0;s.damageTaken+=Number(cs.damageTaken)||0;s.hits+=Number(cs.hits)||0;s.attacks+=Number(cs.attacks)||0;s.criticals+=Number(cs.criticals)||0;s.kills+=Number(cs.kills)||0;s.activeSeconds+=Math.max(.1,Number(wrapper?.seconds)||.1);}}
  monsterExp(enemies){return (Array.isArray(enemies)?enemies:[]).reduce((sum,e)=>sum+Number(e?.exp||e?.experience||0),0);}
  awardBattleExp(result,enemies=[]){if(result!=='WIN')return 0;const amount=this.monsterExp(enemies);if(amount<=0)return 0;this.exp+=amount;for(const c of this.party){if(!c?.alive||typeof c.gainExp!=='function')continue;const gained=c.gainExp(amount);if(gained.levels>0)this.emit('LEVEL_UP',{characterId:c.id,character:c.name,levels:gained.levels,level:c.level,exp:c.exp,expToNext:c.expToNextLevel()});}this.emit('EXP_GAIN',{amount,characters:this.party.map(c=>({id:c.id,name:c.name,level:c.level,exp:c.exp}))});return amount;}
  getXmlEnemies(){const loader=window.MonsterXmlLoader;if(!loader?.state?.loaded)return null;const name=this.dungeon?.monsterDungeonName||this.dungeon?.name;const area=this.dungeon?.areas?.find(x=>x.area===Number(this.floor));const encounter=area?.encounters?.length?area.encounters[this.rng.int(0,area.encounters.length-1)]:null;if(encounter?.enemies?.length){const out=encounter.enemies.map(m=>loader.state.items.find(x=>x.dungeonName===name&&x.name===m.name)).filter(Boolean);if(out.length)return out;}let pool=loader.getForDungeon(name);if(!pool.length){const target=Math.max(1,Math.min(50,Number(this.dungeon?.levelMap?.[Math.max(0,this.floor-1)])||Number(this.floor)||1));pool=loader.getByLevel(target);}return pool.length?pool:null;}
  createXmlEncounter(){const pool=this.getXmlEnemies();if(!pool?.length)return null;return pool.map((m,index)=>new Character({id:`monster-${m.id}-${this.floor}-${index}`,name:m.name,hp:m.maxHp,maxHp:m.maxHp,attack:m.attack,defense:m.defense,speed:10,team:'enemy',exp:m.exp,level:m.level,monsterLevel:m.level,monsterId:m.id,monsterGrade:m.grade,monsterForm:m.form,placement:m.placement}));}
  fight(enemies){const wrapper=this.battleFactory(this.rng,this.party,enemies);const battle=wrapper?.result||wrapper;this.currentBattle=wrapper;this.addBattleStats(wrapper);const result=battle?.result||'DRAW';const events=Array.isArray(battle?.events)?battle.events:[];const enemyData=(Array.isArray(enemies)?enemies:[]).map(e=>({id:e.monsterId||e.id,name:e.name,grade:e.monsterGrade||e.grade,level:e.monsterLevel||e.level||null,form:e.monsterForm||null,placement:e.placement||null}));this.emit('BATTLE_END',{result,round:Number(battle?.round)||0,enemies:enemyData,events});this.awardBattleExp(result,enemies);if(result==='WIN')this.addEquipmentLoot({level:this.currentAreaLevel(enemies)});return wrapper;}
  currentAreaLevel(enemies=[]){const levels=(enemies||[]).map(e=>Number(e?.monsterLevel||e?.level)).filter(Number.isFinite);return Math.min(50,Math.max(1,levels.length?Math.max(...levels):Number(this.floor)||1));}
  addEquipmentLoot({boss=false,baseId=null,pool=null,force=false,level=null}={}){if(!window.LootSystem?.generate)return null;const item=window.LootSystem.generate({rng:this.rng,baseId,pool,force,boss,level:Math.min(50,Math.max(1,Number(level)||this.currentAreaLevel()))});if(!item)return null;if(!Array.isArray(window.GAME_INVENTORY))window.GAME_INVENTORY=[];if(!window.GAME_INVENTORY.some(x=>x?.instanceId===item.instanceId))window.GAME_INVENTORY.push(item);if(typeof window.addLootInstance==='function')window.addLootInstance(item);window.playerInventory=window.GAME_INVENTORY;if(window.playerState)window.playerState.inventory=window.GAME_INVENTORY;this.loot.push({itemId:item.baseId,itemName:item.name,quantity:1,floor:this.floor,instanceId:item.instanceId,rarity:item.rarity,rarityName:item.rarityName,enhancement:item.enhancement,options:item.options,equipment:item});this.emit('LOOT',{itemId:item.baseId,itemName:item.name,quantity:1,floor:this.floor,instanceId:item.instanceId,rarity:item.rarity,rarityName:item.rarityName,enhancement:item.enhancement,options:item.options,equipment:item});return item;}
  addLoot(itemId,itemName,quantity,gold=0){const item={itemId,itemName,quantity,floor:this.floor};this.loot.push(item);this.gold+=gold;this.emit('LOOT',{...item,gold});}
  nextFloor(){if(!this.active)return{done:true};this.floor++;this.encounterIndex=0;if(this.floor>this.dungeon.floors){this.complete=true;this.active=false;this.emit('RUN_COMPLETE',{floor:this.floor-1});return{done:true};}this.emit('FLOOR_REACHED',{floor:this.floor});return{done:false,floor:this.floor};}
  step(){if(!this.active)return{done:true,battle:null};if(this.floor===0)this.nextFloor();let enemies=this.createXmlEncounter();if(!enemies?.length){const encounters=Array.isArray(this.dungeon.encounters)?this.dungeon.encounters:[];const encounter=this.floor===this.dungeon.floors?null:(encounters.length?encounters[this.rng.int(0,encounters.length-1)]:null);if(encounter?.type==='treasure'){if(encounter.itemId&&window.EQUIPMENT?.[encounter.itemId])this.addEquipmentLoot({baseId:encounter.itemId,force:true});else this.addLoot(encounter.itemId,encounter.itemName,encounter.quantity,encounter.gold);}else if(encounter?.type==='battle'&&Array.isArray(encounter.enemies))enemies=encounter.enemies.map(e=>new Character({...e,team:'enemy'}));}
    if(enemies?.length){const isBoss=Boolean(enemies.some(e=>e.placement==='boss'||e.monsterGrade==='boss'||e.monsterForm==='boss'));const battle=this.fight(enemies);const result=battle?.result?.result||battle?.result||'DRAW';if(isBoss&&result==='WIN'){this.addEquipmentLoot({boss:true,level:this.currentAreaLevel(enemies)});this.addLoot('boss-cache','수호자의 보물',1,500);}}
    if(this.active&&this.floor===this.dungeon.floors){this.complete=true;this.active=false;this.emit('RUN_COMPLETE',{floor:this.floor});}else if(this.active)this.nextFloor();return{done:this.complete,battle:this.currentBattle};}
  getDps(id){const s=this.stats[id];return s&&s.activeSeconds?Math.round(s.damage/s.activeSeconds):0;}
  summary(){return{runId:this.runId,dungeonId:this.dungeon.id,floor:this.floor,complete:this.complete,gold:this.gold,exp:this.exp,loot:this.loot,inventory:Array.isArray(window.GAME_INVENTORY)?window.GAME_INVENTORY:[],stats:this.stats,dps:Object.fromEntries(this.party.map(c=>[c.id,this.getDps(c.id)])),events:this.events};}
}
window.DungeonRun=DungeonRun;
