(() => {
  const CONFIG={sources:[{min:1,max:25,path:'data/equipment/equipment_data_lvl1_25.xml'},{min:26,max:50,path:'data/equipment/equipment_data_lvl26_50.xml'}]};
  const state={loaded:false,items:[],byLevel:new Map(),errors:[]};
  const text=el=>el?.textContent?.trim()||'';
  function parse(xml,source){const doc=new DOMParser().parseFromString(xml,'application/xml');if(doc.querySelector('parsererror'))throw new Error(`XML 파싱 실패: ${source}`);return [...doc.querySelectorAll('EquipmentDatabase > Item')].map(n=>{const id=n.getAttribute('id');const type=text(n.querySelector('Type'));const value=n.querySelector('Value');const stat=n.querySelector('ReqStat');const req={stats:{}};if(stat)req.stats[stat.getAttribute('type')]=Number(text(stat))||0;return {id:`xml_${id}`,sourceId:String(id),name:text(n.querySelector('Name')),slot:type==='Weapon'?'weapon':type==='Armor'?'armor':'accessory',rarity:text(n.querySelector('Grade')).toLowerCase(),reqLevel:Number(text(n.querySelector('ReqLevel')))||1,attack:value?.getAttribute('type')==='Attack'?Number(text(value))||0:0,defense:value?.getAttribute('type')==='Defense'?Number(text(value))||0:0,speed:0,hp:0,requirements:req,source:'equipment_xml'};});}
  async function load(){const all=[];for(const s of CONFIG.sources){try{const r=await fetch(s.path,{cache:'no-store'});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);all.push(...parse(await r.text(),s.path));}catch(e){state.errors.push(e.message);}}state.items=all;state.byLevel=new Map();all.forEach(x=>{if(!state.byLevel.has(x.reqLevel))state.byLevel.set(x.reqLevel,[]);state.byLevel.get(x.reqLevel).push(x);});state.loaded=all.length>0;window.XML_EQUIPMENT_POOL=all;window.XML_EQUIPMENT_BY_LEVEL=state.byLevel;window.XML_EQUIPMENT_STATUS=state;return state;}
  function pool(level,{rarity=null,slot=null}={}){const l=Math.max(1,Math.min(50,Number(level)||1));let out=state.items.filter(x=>x.reqLevel<=l&&x.reqLevel>=Math.max(1,l-5));if(rarity)out=out.filter(x=>x.rarity===String(rarity).toLowerCase());if(slot)out=out.filter(x=>x.slot===slot);return out;}
  window.EquipmentXmlLoader={CONFIG,state,load,pool};
})();
