(() => {
  const CONFIG={minLevel:1,maxLevel:50};
  const state={loaded:false,items:[],byDungeon:new Map(),byLevel:new Map(),errors:[]};
  const text=e=>e?.textContent?.trim()||'';
  const clampLevel=n=>Math.max(CONFIG.minLevel,Math.min(CONFIG.maxLevel,Number(n)||CONFIG.minLevel));
  function parse(xml){const doc=new DOMParser().parseFromString(xml,'application/xml');if(doc.querySelector('parsererror'))throw new Error('monster.xml 파싱 실패');const out=[];doc.querySelectorAll('DungeonMonstersDatabase Dungeon').forEach(d=>{const dungeonId=Number(d.getAttribute('id'));const dungeonName=d.getAttribute('name')||'';d.querySelectorAll(':scope > Monster').forEach(m=>{const s=m.querySelector('Stats'),t=m.querySelector('Traits');const rawLevel=Number(text(m.querySelector('Level'))) || 1;if(rawLevel<CONFIG.minLevel||rawLevel>CONFIG.maxLevel)return;const hp=Number(text(s?.querySelector('HP'))) || 1;const attack=Number(text(m.querySelector('Attack'))) || Number(text(s?.querySelector('ATK'))) || 1;const defense=Number(text(m.querySelector('Defense'))) || Number(text(s?.querySelector('DEF'))) || 0;const exp=Number(text(m.querySelector('Exp'))) || 0;out.push({id:m.getAttribute('id'),name:text(m.querySelector('Name')),type:(m.getAttribute('type')||'Normal').toLowerCase(),grade:(m.getAttribute('Grade')||m.getAttribute('type')||'Normal').toLowerCase(),level:rawLevel,hp,maxHp:hp,attack,defense,exp,attackType:text(t?.querySelector('AttackType'))||text(m.querySelector('AttackType')),specialSkill:text(t?.querySelector('SpecialSkill'))||text(m.querySelector('SpecialSkill')),dungeonId,dungeonName,source:'monster.xml'});});});return out;}
  async function load(path='data/monsters/monster.xml'){try{const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw new Error(`${r.status} ${r.statusText}: ${path}`);state.items=parse(await r.text());state.byDungeon=new Map();state.byLevel=new Map();state.items.forEach(m=>{if(!state.byDungeon.has(m.dungeonId))state.byDungeon.set(m.dungeonId,[]);state.byDungeon.get(m.dungeonId).push(m);if(!state.byLevel.has(m.level))state.byLevel.set(m.level,[]);state.byLevel.get(m.level).push(m);});state.loaded=true;window.MONSTER_DATABASE=state.items;window.MONSTERS_BY_DUNGEON=state.byDungeon;window.MONSTERS_BY_LEVEL=state.byLevel;window.MONSTER_LEVEL_CONFIG=CONFIG;return state;}catch(e){state.errors.push(e.message);return state;}}
  function getForDungeon(id,level=null){let out=state.byDungeon.get(Number(id))||[];if(level!=null)out=out.filter(m=>m.level===clampLevel(level));return out;}
  function getByLevel(level){return state.byLevel.get(clampLevel(level))||[];}
  function create(id){const m=state.items.find(x=>x.id===id);return m?{...m}:null;}
  window.MonsterXmlLoader={CONFIG,state,load,getForDungeon,getByLevel,create,clampLevel};
})();
