(() => {
  const CONFIG={minLevel:1,maxLevel:50,sources:['data/monsters/monster.xml','data/monsters/monster_lvl1_50.xml','data/monsters/monster_lvl1_50.xml.txt']};
  const state={loaded:false,items:[],byDungeon:new Map(),byLevel:new Map(),errors:[],source:null};
  const text=e=>e?.textContent?.trim()||'';
  const clampLevel=n=>Math.max(CONFIG.minLevel,Math.min(CONFIG.maxLevel,Number(n)||CONFIG.minLevel));
  function parse(xml,source){const doc=new DOMParser().parseFromString(xml,'application/xml');if(doc.querySelector('parsererror'))throw new Error(`몬스터 XML 파싱 실패: ${source}`);const out=[];doc.querySelectorAll('DungeonMonstersDatabase Dungeon').forEach(d=>{const dungeonId=Number(d.getAttribute('id'));const dungeonName=d.getAttribute('name')||'';d.querySelectorAll(':scope > Monster').forEach(m=>{const s=m.querySelector('Stats'),t=m.querySelector('Traits');const rawLevel=Number(text(m.querySelector('Level'))) || 1;if(rawLevel<CONFIG.minLevel||rawLevel>CONFIG.maxLevel)return;const hp=Number(text(s?.querySelector('HP'))) || 1;const attack=Number(text(m.querySelector('Attack'))) || Number(text(s?.querySelector('ATK'))) || 1;const defense=Number(text(m.querySelector('Defense'))) || Number(text(s?.querySelector('DEF'))) || 0;const exp=Number(text(m.querySelector('Exp'))) || 0;out.push({id:m.getAttribute('id'),name:text(m.querySelector('Name')),type:(m.getAttribute('type')||'Normal').toLowerCase(),grade:(m.getAttribute('Grade')||m.getAttribute('type')||'Normal').toLowerCase(),form:(m.getAttribute('Form')||text(m.querySelector('Form'))||'Standard').toLowerCase(),level:rawLevel,hp,maxHp:hp,attack,defense,exp,attackType:text(t?.querySelector('AttackType'))||text(m.querySelector('AttackType')),specialSkill:text(t?.querySelector('SpecialSkill'))||text(m.querySelector('SpecialSkill')),dungeonId,dungeonName,source:'monster_xml',sourcePath:source});});});return out;}
  async function load(path=null){state.errors=[];state.source=null;for(const candidate of (path?[path]:CONFIG.sources)){try{const r=await fetch(candidate,{cache:'no-store'});if(!r.ok)throw new Error(`${r.status} ${r.statusText}: ${candidate}`);const items=parse(await r.text(),candidate);if(!items.length)throw new Error(`Monster 없음: ${candidate}`);state.items=items;state.source=candidate;state.byDungeon=new Map();state.byLevel=new Map();items.forEach(m=>{if(!state.byDungeon.has(m.dungeonId))state.byDungeon.set(m.dungeonId,[]);state.byDungeon.get(m.dungeonId).push(m);if(!state.byLevel.has(m.level))state.byLevel.set(m.level,[]);state.byLevel.get(m.level).push(m);});state.loaded=true;window.MONSTER_DATABASE=items;window.MONSTERS_BY_DUNGEON=state.byDungeon;window.MONSTERS_BY_LEVEL=state.byLevel;window.MONSTER_LEVEL_CONFIG=CONFIG;return state;}catch(e){state.errors.push(e.message);}}state.loaded=false;return state;}
  function getForDungeon(id,level=null){let out=state.byDungeon.get(Number(id))||[];if(level!=null)out=out.filter(m=>m.level===clampLevel(level));return out;}
  function getByLevel(level){return state.byLevel.get(clampLevel(level))||[];}
  function create(id){const m=state.items.find(x=>x.id===id);return m?{...m}:null;}
  window.MonsterXmlLoader={CONFIG,state,load,getForDungeon,getByLevel,create,clampLevel};
})();
